//! Firmware generation for QMK keymap.c and vial.json.
//!
//! This module generates QMK C code and Vial JSON configuration
//! from keyboard layouts using the LED index order.

// Allow format! appended to String - more readable than write! in code generation
#![allow(clippy::format_push_string)]

use crate::config::Config;
use crate::constants::APP_BINARY_NAME;
use crate::keycode_db::KeycodeDb;
use crate::models::keyboard_geometry::KeyboardGeometry;
use crate::models::layout::Layout;
use crate::models::visual_layout_mapping::VisualLayoutMapping;
use anyhow::{Context, Result};
use serde_json::json;
use std::fs;

/// Firmware generator for keymap.c and vial.json.
pub struct FirmwareGenerator<'a> {
    layout: &'a Layout,
    geometry: &'a KeyboardGeometry,
    mapping: &'a VisualLayoutMapping,
    config: &'a Config,
    keycode_db: &'a KeycodeDb,
}

impl<'a> FirmwareGenerator<'a> {
    /// Creates a new firmware generator.
    #[must_use]
    pub const fn new(
        layout: &'a Layout,
        geometry: &'a KeyboardGeometry,
        mapping: &'a VisualLayoutMapping,
        config: &'a Config,
        keycode_db: &'a KeycodeDb,
    ) -> Self {
        Self {
            layout,
            geometry,
            mapping,
            config,
            keycode_db,
        }
    }

    /// Generates keymap.c, vial.json, and config.h files.
    ///
    /// Files are written to both:
    /// 1. Timestamped output directory (for archival)
    /// 2. QMK keymap directory (for building)
    ///
    /// Returns paths to the generated files in the timestamped directory.
    pub fn generate(&self) -> Result<(String, String, String)> {
        // Create timestamped output directory
        let timestamp_dir = self.create_timestamped_output_dir()?;
        
        // Generate config.h (merge with keyboard config if exists)
        let config_h = self.generate_merged_config_h()?;
        let config_h_path = self.write_file_to_both(&timestamp_dir, "config.h", &config_h)?;

        // Generate keymap.c
        let keymap_c = self.generate_keymap_c()?;
        let keymap_path = self.write_file_to_both(&timestamp_dir, "keymap.c", &keymap_c)?;

        // Generate vial.json
        let vial_json = self.generate_vial_json()?;
        let vial_path = self.write_file_to_both(&timestamp_dir, "vial.json", &vial_json)?;

        Ok((keymap_path, vial_path, config_h_path))
    }

    /// Generates keymap.c C code.
    ///
    /// Creates a QMK keymap file with PROGMEM arrays for each layer.
    /// Keys are ordered by LED index as required by QMK.
     fn generate_keymap_c(&self) -> Result<String> {
         let mut code = String::new();

         // File header
         code.push_str(&format!("// Generated by {}\n", APP_BINARY_NAME));
         code.push_str(&format!("// Layout: {}\n", self.layout.metadata.name));
         code.push_str(&format!("// Keyboard: {}\n", self.config.build.keyboard));
         code.push_str(&format!(
             "// Layout Variant: {}\n",
             self.config.build.layout
         ));
         code.push('\n');

        // Includes
        code.push_str("#include QMK_KEYBOARD_H\n\n");

        // Keymap definition
        code.push_str("const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n");

        // Generate each layer
        for (layer_idx, layer) in self.layout.layers.iter().enumerate() {
            code.push_str(&format!("    // Layer {}: {}\n", layer_idx, layer.name));
            code.push_str(&format!(
                "    [{}] = {}(",
                layer_idx, self.config.build.layout
            ));

            // Generate keys in layout order (matches info.json layout array)
            let keys_by_layout = self.generate_layer_keys_by_layout(layer)?;

            // Format keys (wrap at reasonable line length)
            let keys_str = keys_by_layout.join(", ");
            if keys_str.len() > 80 {
                // Multi-line formatting
                code.push_str("\n        ");
                for (idx, keycode) in keys_by_layout.iter().enumerate() {
                    code.push_str(keycode);
                    if idx < keys_by_layout.len() - 1 {
                        code.push_str(", ");
                    }
                    // Line wrap every 6 keys
                    if (idx + 1) % 6 == 0 && idx < keys_by_layout.len() - 1 {
                        code.push_str("\n        ");
                    }
                }
                code.push_str("\n    ");
            } else {
                // Single line formatting
                code.push_str(&keys_str);
            }

            code.push(')');
            if layer_idx < self.layout.layers.len() - 1 {
                code.push_str(",\n");
            } else {
                code.push('\n');
            }
        }

        code.push_str("};\n");
 
         // Add conditional encoder_map (only when ENCODER_MAP_ENABLE is defined)
         code.push('\n');
         code.push_str(&self.generate_conditional_encoder_map()?);
 
         // Add optional RGB matrix base color table when RGB is present.
         code.push('\n');
         code.push_str(&self.generate_rgb_matrix_color_table()?);
 
         Ok(code)
     }


    /// Generates a conditional `encoder_map` wrapped in #ifdef `ENCODER_MAP_ENABLE`.
    ///
    /// This allows the keymap to work both with and without encoders enabled.
    /// When `ENCODER_MAP_ENABLE` is defined in rules.mk, this `encoder_map` will be included.
    #[allow(clippy::unnecessary_wraps)]
    fn generate_conditional_encoder_map(&self) -> Result<String> {
        let mut code = String::new();

        code.push_str("#ifdef ENCODER_MAP_ENABLE\n");
        code.push_str("const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {\n");

        // Generate encoder bindings for each layer
        // We use RGB controls as sensible defaults that work on most keyboards
        for (layer_idx, _layer) in self.layout.layers.iter().enumerate() {
            code.push_str(&format!("    [{layer_idx}] = {{\n"));
            code.push_str("        ENCODER_CCW_CW(RGB_MOD, RGB_RMOD),\n");
            code.push_str("        ENCODER_CCW_CW(RGB_HUI, RGB_HUD),\n");
            code.push_str("        ENCODER_CCW_CW(RGB_VAI, RGB_VAD),\n");
            code.push_str("        ENCODER_CCW_CW(RGB_SAI, RGB_SAD),\n");
            code.push_str("    }");
            
            if layer_idx < self.layout.layers.len() - 1 {
                code.push_str(",\n");
            } else {
                code.push_str(",\n");
            }
        }

        code.push_str("};\n");
        code.push_str("#endif\n");

        Ok(code)
    }

    /// Generates keycodes for a layer ordered by layout index.
    ///
    /// This is the critical transformation: visual position → matrix → layout order.
    /// The layout order matches the info.json layout array, which is what QMK's
    /// LAYOUT macro expects.
    ///
    /// Layer references (e.g., `MO(@uuid)`) are resolved to numeric indices
    /// (e.g., `MO(1)`) for firmware compatibility.
    fn generate_layer_keys_by_layout(
        &self,
        layer: &crate::models::layer::Layer,
    ) -> Result<Vec<String>> {
        let key_count = self.mapping.key_count();
        let mut keys_by_layout = vec![String::from("KC_NO"); key_count];

        // Map each key to its layout position
        for key in &layer.keys {
            let visual_pos = key.position;

            // Visual → Layout index
            let layout_idx = self
                .mapping
                .visual_to_layout_index(visual_pos.row, visual_pos.col)
                .with_context(|| {
                    format!(
                        "Failed to map visual position ({}, {}) to layout index",
                        visual_pos.row, visual_pos.col
                    )
                })?;

            // Resolve layer references in keycode (e.g., MO(@uuid) -> MO(1))
            let resolved_keycode = self.resolve_keycode(&key.keycode);

            // Store keycode at layout position
            keys_by_layout[layout_idx as usize] = resolved_keycode;
        }

        Ok(keys_by_layout)
    }

    /// Resolves a keycode, converting layer references to numeric indices.
    ///
    /// If the keycode contains a layer reference like `MO(@uuid)`, it will be
    /// resolved to the numeric index like `MO(1)`. If resolution fails (e.g.,
    /// the referenced layer no longer exists), the original keycode is returned.
    fn resolve_keycode(&self, keycode: &str) -> String {
        // Try to resolve layer references using the keycode database
        if let Some(resolved) = self.layout.resolve_layer_keycode(keycode, self.keycode_db) {
            resolved
        } else {
            // Not a layer keycode or resolution failed - use as-is
            keycode.to_string()
        }
    }

    /// Generates key assignments for a layer ordered by LED index.
    ///
    /// Used only for LED-related features. For keymap generation, use
    /// `generate_layer_keys_by_layout` instead.
    #[allow(dead_code)]
    fn generate_layer_keys_by_led(
        &self,
        layer: &crate::models::layer::Layer,
    ) -> Result<Vec<String>> {
        let led_count = self.mapping.key_count();
        let mut keys_by_led = vec![String::from("KC_NO"); led_count];

        // Map each key to its LED position
        for key in &layer.keys {
            let visual_pos = key.position;

            // Visual d1 Matrix
            let matrix_pos = self
                .mapping
                .visual_to_matrix_pos(visual_pos.row, visual_pos.col)
                .with_context(|| {
                    format!(
                        "Failed to map visual position ({}, {}) to matrix",
                        visual_pos.row, visual_pos.col
                    )
                })?;

            // Matrix d1 LED
            let led_idx = self
                .mapping
                .visual_to_led_index(visual_pos.row, visual_pos.col)
                .with_context(|| {
                    format!(
                        "Failed to map matrix position ({}, {}) to LED index",
                        matrix_pos.0, matrix_pos.1
                    )
                })?;

            // Store keycode at LED position
            keys_by_led[led_idx as usize].clone_from(&key.keycode);
        }

        Ok(keys_by_led)
    }

    /// Generates resolved colors for a layer ordered by LED index.
    ///
    /// Colors use the same visual -> LED mapping as `generate_layer_keys_by_led`
    /// and honor the layout's four-level color priority system and the
    /// `inactive_key_behavior` setting.
    ///
    /// If the layer has `colors_enabled = false`, returns all black (off) colors.
    fn generate_layer_colors_by_led(
        &self,
        layer_idx: usize,
    ) -> Result<Vec<crate::models::RgbColor>> {
        let led_count = self.mapping.key_count();
        let mut colors_by_led = vec![crate::models::RgbColor::default(); led_count];

        let layer = self
            .layout
            .get_layer(layer_idx)
            .with_context(|| format!("Invalid layer index {layer_idx}"))?;

        // If layer colors are disabled for this layer, return all black (LEDs off)
        if !layer.layer_colors_enabled {
            return Ok(vec![crate::models::RgbColor::new(0, 0, 0); led_count]);
        }

        // Map each key's resolved color to its LED position
        // Uses resolve_display_color which considers inactive_key_behavior
        for key in &layer.keys {
            let visual_pos = key.position;

            let led_idx = self
                .mapping
                .visual_to_led_index(visual_pos.row, visual_pos.col)
                .with_context(|| {
                    format!(
                        "Failed to map visual position ({}, {}) to LED index",
                        visual_pos.row, visual_pos.col
                    )
                })?;

            // Use resolve_display_color to respect inactive_key_behavior
            let (color, _is_key_specific) = self.layout.resolve_display_color(layer_idx, key);
            colors_by_led[led_idx as usize] = color;
        }

        Ok(colors_by_led)
    }
 
    /// Returns true if the layout uses any custom color semantics.
    ///
    /// This treats the layout as "colored" if:
    /// - Any layer default color differs from the global default (white), or
    /// - Any layer has a category, or
    /// - Any key has a color override or category, or
    /// - The layout defines any categories at all.
    fn layout_has_custom_colors(&self) -> bool {
        if !self.layout.categories.is_empty() {
            return true;
        }

        let default_color = crate::models::RgbColor::default();

        for layer in &self.layout.layers {
            if layer.default_color != default_color {
                return true;
            }

            if layer.category_id.is_some() {
                return true;
            }

            for key in &layer.keys {
                if key.color_override.is_some() || key.category_id.is_some() {
                    return true;
                }
            }
        }

        false
    }
 
    /// Generates an RGB matrix base color table in C when RGB is present.
    ///
    /// The table layout is:
    /// `const uint8_t PROGMEM layer_base_colors[NUM_LAYERS][RGB_MATRIX_LED_COUNT][3]`.
    fn generate_rgb_matrix_color_table(&self) -> Result<String> {
        // If the keyboard has no RGB matrix (no keys), emit an empty string
        // to avoid unused data in non-RGB builds.
        if !self.geometry.has_rgb_matrix() {
            return Ok(String::new());
        }

        let mut code = String::new();
        let layer_count = self.layout.layers.len();
        let led_count = self.mapping.key_count();

        code.push_str("#ifdef RGB_MATRIX_ENABLE\n");
        code.push_str(&format!(
            "const uint8_t PROGMEM layer_base_colors[{layer_count}][{led_count}][3] = {{\n"
        ));

        for layer_idx in 0..layer_count {
            let colors = self.generate_layer_colors_by_led(layer_idx)?;
            code.push_str("    {\n");

            for (led_idx, color) in colors.iter().enumerate() {
                code.push_str(&format!(
                    "        {{{:3}, {:3}, {:3}}}",
                    color.r, color.g, color.b
                ));

                if led_idx < colors.len() - 1 {
                    code.push(',');
                }

                code.push('\n');
            }

            code.push_str("    }");
            if layer_idx < layer_count - 1 {
                code.push_str(",\n");
            } else {
                code.push('\n');
            }
        }

        code.push_str("};\n");
        code.push_str(&format!(
            "const uint8_t PROGMEM layer_base_colors_layer_count = {layer_count};\n"
        ));
        code.push_str("#endif\n");

        Ok(code)
    }

    /// Generates vial.json configuration.
    ///
    /// Creates a Vial JSON file with layout definition and metadata.
    fn generate_vial_json(&self) -> Result<String> {
        let vial_config = json!({
            "name": self.layout.metadata.name,
            "vendor_product_id": "0xFEED:0x0000", // Default, should be overridden
            "lighting": "none",
            "matrix": {
                "rows": self.geometry.matrix_rows,
                "cols": self.geometry.matrix_cols
            },
            "layouts": {
                "keymap": self.generate_vial_layout_array()?
            },
            "layers": self.layout.layers.len(),
            "author": self.layout.metadata.author,
            "description": self.layout.metadata.description,
            "tags": self.layout.metadata.tags
        });

        let json_str =
            serde_json::to_string_pretty(&vial_config).context("Failed to serialize vial.json")?;

        Ok(json_str)
    }

    /// Generates the Vial layout array.
    ///
    /// Creates the visual key layout for the Vial UI.
    fn generate_vial_layout_array(&self) -> Result<serde_json::Value> {
        let mut layout_keys = Vec::new();

        // Get all keys from first layer (geometry is same for all layers)
        let first_layer = self
            .layout
            .layers
            .first()
            .context("Layout must have at least one layer")?;

        for key in &first_layer.keys {
            // Get key geometry via LED mapping
            let led_idx = self
                .mapping
                .visual_to_led_index(key.position.row, key.position.col)
                .context("Failed to map key to LED index")?;

            let key_geom = self
                .geometry
                .get_key_by_led(led_idx)
                .context("Failed to get key geometry")?;

            // Create Vial key definition
            // Format: [x, y, width, height, matrix_row, matrix_col]
            layout_keys.push(json!([
                key_geom.visual_x,
                key_geom.visual_y,
                key_geom.width,
                key_geom.height,
                key_geom.matrix_position.0,
                key_geom.matrix_position.1
            ]));
        }

        Ok(json!(layout_keys))
    }



    /// Gets the keymap output directory.
    ///
    /// Creates directory structure if it doesn't exist:
    /// {`qmk_firmware}/keyboards/{keyboard}/keymaps/{keymap`}/
    ///
    /// The keyboard path may include variant subdirectories (e.g., "`keebart/corne_choc_pro/standard`").
    /// The keymap directory is created under the exact keyboard path used for building.
    fn get_keymap_directory(&self) -> Result<std::path::PathBuf> {
        let qmk_path = self
            .config
            .paths
            .qmk_firmware
            .as_ref()
            .context("QMK firmware path not configured")?;

        // Use the full keyboard path from config (which may include a variant)
        // E.g., "keebart/corne_choc_pro/standard" -> keyboards/keebart/corne_choc_pro/standard/keymaps/{keymap}
        let keymap_dir = qmk_path
            .join("keyboards")
            .join(&self.config.build.keyboard)
            .join("keymaps")
            .join(&self.config.build.keymap);

        // Create directory if it doesn't exist
        fs::create_dir_all(&keymap_dir)
            .with_context(|| format!("Failed to create directory {}", keymap_dir.display()))?;

        Ok(keymap_dir)
    }

    /// Creates a timestamped output directory for this build.
    ///
    /// Format: {`output_dir}/{keyboard`}_{keymap}_{`YYYYMMDD_HHMMSS`}/
    fn create_timestamped_output_dir(&self) -> Result<std::path::PathBuf> {
        let timestamp = chrono::Local::now().format("%Y%m%d_%H%M%S");
        let dir_name = format!("{}_{}_{}",
            self.config.build.keyboard.replace('/', "_"),
            self.config.build.keymap,
            timestamp
        );
        
        let output_dir = self.config.build.output_dir.join(dir_name);
        
        fs::create_dir_all(&output_dir)
            .with_context(|| format!("Failed to create output directory {}", output_dir.display()))?;
        
        Ok(output_dir)
    }

    /// Writes a file to both the timestamped archive and the QMK keymap directory.
    ///
    /// Returns the path in the timestamped directory.
    fn write_file_to_both(
        &self,
        timestamp_dir: &std::path::Path,
        filename: &str,
        content: &str,
    ) -> Result<String> {
        // Write to timestamped archive directory
        let archive_path = timestamp_dir.join(filename);
        fs::write(&archive_path, content)
            .with_context(|| format!("Failed to write {}", archive_path.display()))?;

        // Write to QMK keymap directory
        let keymap_dir = self.get_keymap_directory()?;
        let qmk_path = keymap_dir.join(filename);
        fs::write(&qmk_path, content)
            .with_context(|| format!("Failed to write {}", qmk_path.display()))?;

        Ok(archive_path.display().to_string())
    }

    /// Generates config.h for the keymap.
    ///
    /// This generates a minimal keymap-specific config.h.
    /// Note: `RGB_MATRIX_LED_COUNT` should be defined in the keyboard's variant-specific
    /// keyboard.json file, not in the keymap config.h.
    fn generate_merged_config_h(&self) -> Result<String> {
        use crate::models::HoldDecisionMode;

        let mut content = String::new();
 
        // Add our generated configuration
        content.push_str("// Generated by KeyboardConfigurator\n");
        content.push_str(&format!("// Layout: {}\n", self.layout.metadata.name));
        content.push_str(&format!("// Generated: {}\n", chrono::Local::now().format("%Y-%m-%d %H:%M:%S")));
        content.push('\n');
        content.push_str("#pragma once\n");
        content.push('\n');
        content.push_str("// Add keymap-specific configuration here\n");
 
        // === Tap-Hold Settings ===
        let ths = &self.layout.tap_hold_settings;

        // Validate tap-hold settings before generating
        ths.validate()?;

        // Only emit non-default tap-hold settings
        if ths.has_custom_settings() {
            content.push_str("\n// Tap-Hold Configuration\n");

            // Tapping Term
            if ths.has_custom_tapping_term() {
                content.push_str(&format!("#define TAPPING_TERM {}\n", ths.tapping_term));
            }

            // Quick Tap Term
            if ths.has_custom_quick_tap_term() {
                if let Some(term) = ths.quick_tap_term {
                    content.push_str(&format!("#define QUICK_TAP_TERM {term}\n"));
                }
                // None means use TAPPING_TERM (QMK default), no need to emit
            }

            // Hold Mode - use config_define() to get the #define name
            if ths.hold_mode != HoldDecisionMode::Default {
                if let Some(define_name) = ths.hold_mode.config_define() {
                    content.push_str(&format!("#define {define_name}\n"));
                }
            }

            // Retro Tapping - only emit if enabled
            if ths.retro_tapping {
                content.push_str("#define RETRO_TAPPING\n");
            }

            // Tapping Toggle - only emit if different from default (5)
            if ths.tapping_toggle != 5 {
                content.push_str(&format!("#define TAPPING_TOGGLE {}\n", ths.tapping_toggle));
            }

            // Flow Tap Term (QMK 0.26+)
            if let Some(term) = ths.flow_tap_term {
                content.push_str(&format!("#define FLOW_TAP_TERM {term}\n"));
            }

            // Chordal Hold (QMK 0.26+) - only emit if enabled
            if ths.chordal_hold {
                content.push_str("#define CHORDAL_HOLD\n");
            }
        }

        // === RGB Settings ===
        // RGB Matrix timeout (auto-off after inactivity)
        if self.layout.rgb_timeout_ms > 0 {
            content.push_str("\n// RGB Matrix Timeout (auto-off after inactivity)\n");
            content.push_str(&format!("#define RGB_MATRIX_TIMEOUT {}\n", self.layout.rgb_timeout_ms));
        }

        // If the keyboard has RGB matrix and the layout defines
        // any custom colors, default to the TUI-driven lighting
        // mode so firmware reflects the editor by default.
        if self.geometry.has_rgb_matrix() && self.layout_has_custom_colors() {
            content.push_str("\n// Default to TUI layer-aware RGB colors when available\n");
            content.push_str("#ifdef RGB_MATRIX_ENABLE\n");
            content.push_str("#    undef RGB_MATRIX_DEFAULT_MODE\n");
            content.push_str("#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS\n");
            content.push_str("#    define LAYER_BASE_COLORS_LAYER_COUNT ");
            content.push_str(&format!("{}\n", self.layout.layers.len()));
            content.push_str("#endif\n");
        }
 
        // If this keyboard already has a Vial keymap, copy its unlock combo macros
        // so that quantum/vial.c can compile for the generated keymap as well.
        if let Some(qmk_path) = &self.config.paths.qmk_firmware {
            // Vial unlock combo is defined at the base keyboard level (without variant).
            // E.g., keebart/corne_choc_pro/keymaps/vial/config.h
            let keyboard_parts: Vec<&str> = self.config.build.keyboard.split('/').collect();
            let base_keyboard = if keyboard_parts.len() > 2 {
                keyboard_parts[..keyboard_parts.len() - 1].join("/")
            } else {
                self.config.build.keyboard.clone()
            };

            let vial_config_path = qmk_path
                .join("keyboards")
                .join(&base_keyboard)
                .join("keymaps")
                .join("vial")
                .join("config.h");
 
            if let Ok(vial_config) = fs::read_to_string(&vial_config_path) {
                let mut rows_define: Option<String> = None;
                let mut cols_define: Option<String> = None;
 
                for line in vial_config.lines() {
                    let trimmed = line.trim();
                    if trimmed.starts_with("#define VIAL_UNLOCK_COMBO_ROWS") {
                        rows_define = Some(trimmed.to_string());
                    } else if trimmed.starts_with("#define VIAL_UNLOCK_COMBO_COLS") {
                        cols_define = Some(trimmed.to_string());
                    }
                }
 
                if rows_define.is_some() || cols_define.is_some() {
                    content.push_str("\n// Vial unlock combo copied from keymaps/vial/config.h\n");
                    if let Some(rows) = rows_define {
                        content.push_str(&rows);
                        content.push('\n');
                    }
                    if let Some(cols) = cols_define {
                        content.push_str(&cols);
                        content.push('\n');
                    }
                }
            }
        }
 
        Ok(content)
    }

}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::keyboard_geometry::KeyGeometry;
    use crate::models::layer::{KeyDefinition, Layer, Position};
    use crate::models::RgbColor;
    use std::path::PathBuf;

    fn create_test_setup() -> (Layout, KeyboardGeometry, VisualLayoutMapping, Config, KeycodeDb) {
        let mut layout = Layout::new("Test").unwrap();
        let mut layer = Layer::new(0, "Base", RgbColor::new(255, 255, 255)).unwrap();
        layer.add_key(KeyDefinition::new(Position::new(0, 0), "KC_A"));
        layer.add_key(KeyDefinition::new(Position::new(0, 1), "KC_B"));
        layout.add_layer(layer).unwrap();

        let mut geometry = KeyboardGeometry::new("test", "LAYOUT", 2, 2);
        geometry.add_key(KeyGeometry::new((0, 0), 0, 0.0, 0.0));
        geometry.add_key(KeyGeometry::new((0, 1), 1, 1.0, 0.0));

        let mapping = VisualLayoutMapping::build(&geometry);

        let mut config = Config::default();
        config.paths.qmk_firmware = Some(PathBuf::from("/tmp/qmk_test"));
        config.build.keyboard = "test".to_string();
        config.build.layout = "LAYOUT".to_string();
        config.build.keymap = "default".to_string();

        let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

        (layout, geometry, mapping, config, keycode_db)
    }

    #[test]
    fn test_generate_keymap_c() {
        let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);

        let keymap_c = generator.generate_keymap_c().unwrap();

        // Verify header
        assert!(keymap_c.contains("// Generated by keyboard-configurator"));
        assert!(keymap_c.contains("// Layout: Test"));
        assert!(keymap_c.contains("#include QMK_KEYBOARD_H"));

        // Verify keymap structure
        assert!(keymap_c.contains("const uint16_t PROGMEM keymaps[]"));
        assert!(keymap_c.contains("[0] = LAYOUT("));
        assert!(keymap_c.contains("KC_A"));
        assert!(keymap_c.contains("KC_B"));

        // Verify encoder_map is included
        assert!(keymap_c.contains("#ifdef ENCODER_MAP_ENABLE"));
        assert!(keymap_c.contains("const uint16_t PROGMEM encoder_map[]"));
        assert!(keymap_c.contains("ENCODER_CCW_CW(RGB_MOD, RGB_RMOD)"));
        assert!(keymap_c.contains("#endif"));

        // Verify RGB matrix base color table is included for RGB keyboards
        assert!(keymap_c.contains("#ifdef RGB_MATRIX_ENABLE"));
        assert!(keymap_c.contains("const uint8_t PROGMEM layer_base_colors"));
        assert!(keymap_c.contains("#endif"));
    }

    #[test]
    fn test_generate_layer_keys_by_led() {
        let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);

        let layer = &layout.layers[0];
        let keys_by_led = generator.generate_layer_keys_by_led(layer).unwrap();

        assert_eq!(keys_by_led.len(), 2);
        assert_eq!(keys_by_led[0], "KC_A");
        assert_eq!(keys_by_led[1], "KC_B");
    }

    #[test]
    fn test_generate_vial_json() {
        let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);

        let vial_json = generator.generate_vial_json().unwrap();

        // Verify JSON structure
        assert!(vial_json.contains(r#""name": "Test""#));
        assert!(vial_json.contains(r#""rows": 2"#));
        assert!(vial_json.contains(r#""cols": 2"#));
        assert!(vial_json.contains(r#""layers": 1"#));
    }

    #[test]
    fn test_generate_vial_layout_array() {
        let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);

        let layout_array = generator.generate_vial_layout_array().unwrap();
        let layout_vec = layout_array.as_array().unwrap();

        assert_eq!(layout_vec.len(), 2);
        // Verify first key has expected structure [x, y, w, h, row, col]
        let first_key = &layout_vec[0];
        assert!(first_key.is_array());
        assert_eq!(first_key.as_array().unwrap().len(), 6);
    }

    #[test]
    fn test_generate_merged_config_h_sets_default_mode_when_colored_and_rgb() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Mark layout as "colored" by changing the default color
        // and adding a category used by a key.
        let nav_color = RgbColor::new(0, 255, 0);
        let category = crate::models::Category::new("navigation", "Navigation", nav_color).unwrap();
        layout.add_category(category).unwrap();
        layout
            .get_layer_mut(0)
            .unwrap()
            .get_key_mut(Position::new(0, 1))
            .unwrap()
            .category_id = Some("navigation".to_string());

        // RGB-capable geometry: already has two keys in create_test_setup.
        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let config_h = generator.generate_merged_config_h().unwrap();

        assert!(config_h.contains("RGB_MATRIX_TUI_LAYER_COLORS"));
        assert!(config_h.contains("#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS"));
    }

    #[test]
    fn test_generate_merged_config_h_does_not_set_default_mode_without_colors_or_rgb() {
        let (layout, mut geometry, mapping, config, keycode_db) = create_test_setup();

        // Remove all keys from geometry so has_rgb_matrix() is false.
        geometry.keys.clear();

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let config_h = generator.generate_merged_config_h().unwrap();

        assert!(!config_h.contains("RGB_MATRIX_TUI_LAYER_COLORS"));
        assert!(!config_h.contains("RGB_MATRIX_DEFAULT_MODE"));
    }

    #[test]
    fn test_generate_layer_colors_by_led_uses_resolved_colors() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Add a category and assign it to the second key so we can
        // verify that resolve_key_color logic is respected.
        let nav_color = RgbColor::new(0, 255, 0);
        let category = crate::models::Category::new("navigation", "Navigation", nav_color).unwrap();
        layout.add_category(category).unwrap();

        // Update key on layer 0, position (0, 1) to use the category.
        layout
            .get_layer_mut(0)
            .unwrap()
            .get_key_mut(Position::new(0, 1))
            .unwrap()
            .category_id = Some("navigation".to_string());

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let colors_by_led = generator.generate_layer_colors_by_led(0).unwrap();

        assert_eq!(colors_by_led.len(), 2);
        // First key uses layer default color (white from create_test_setup).
        assert_eq!(colors_by_led[0], RgbColor::new(255, 255, 255));
        // Second key uses category color.
        assert_eq!(colors_by_led[1], nav_color);
    }

    #[test]
    fn test_generate_rgb_matrix_color_table_structure() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Add a second layer with a different default color
        let mut layer2 = Layer::new(1, "Navigation", RgbColor::new(0, 128, 255)).unwrap();
        layer2.add_key(KeyDefinition::new(Position::new(0, 0), "KC_LEFT"));
        layer2.add_key(KeyDefinition::new(Position::new(0, 1), "KC_RIGHT"));
        layout.add_layer(layer2).unwrap();

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let color_table = generator.generate_rgb_matrix_color_table().unwrap();

        // Verify structure
        assert!(color_table.contains("#ifdef RGB_MATRIX_ENABLE"));
        assert!(color_table.contains("#endif"));
        assert!(color_table.contains("const uint8_t PROGMEM layer_base_colors[2][2][3]"));
        assert!(color_table.contains("layer_base_colors_layer_count = 2;"));

        // Verify layer 0 colors (white default)
        assert!(color_table.contains("{255, 255, 255}"));
        // Verify layer 1 colors (blue-ish default)
        assert!(color_table.contains("{  0, 128, 255}"));
    }

    #[test]
    fn test_generate_rgb_matrix_color_table_empty_for_non_rgb() {
        let (layout, mut geometry, mapping, config, keycode_db) = create_test_setup();

        // Remove keys to simulate non-RGB keyboard
        geometry.keys.clear();

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let color_table = generator.generate_rgb_matrix_color_table().unwrap();

        // Should be empty for non-RGB keyboards
        assert!(color_table.is_empty());
    }

    #[test]
    fn test_layout_has_custom_colors_with_category() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Initially should have no custom colors (just white default)
        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        assert!(!generator.layout_has_custom_colors());

        // Add a category
        let category = crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
        layout.add_category(category).unwrap();

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        assert!(generator.layout_has_custom_colors());
    }

    #[test]
    fn test_layout_has_custom_colors_with_layer_default() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Change layer default color from white
        layout.get_layer_mut(0).unwrap().default_color = RgbColor::new(128, 128, 128);

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        assert!(generator.layout_has_custom_colors());
    }

    #[test]
    fn test_layout_has_custom_colors_with_key_override() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Add key color override
        layout
            .get_layer_mut(0)
            .unwrap()
            .get_key_mut(Position::new(0, 0))
            .unwrap()
            .color_override = Some(RgbColor::new(255, 0, 0));

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        assert!(generator.layout_has_custom_colors());
    }

    #[test]
    fn test_generate_layer_colors_respects_priority_order() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Set up all four color levels for key at (0, 1):
        // 1. Global default is white (255, 255, 255)
        // 2. Layer default: blue
        layout.get_layer_mut(0).unwrap().default_color = RgbColor::new(0, 0, 255);

        // 3. Category: green
        let category = crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
        layout.add_category(category).unwrap();
        layout
            .get_layer_mut(0)
            .unwrap()
            .get_key_mut(Position::new(0, 1))
            .unwrap()
            .category_id = Some("nav".to_string());

        // 4. Key override: red (highest priority)
        layout
            .get_layer_mut(0)
            .unwrap()
            .get_key_mut(Position::new(0, 1))
            .unwrap()
            .color_override = Some(RgbColor::new(255, 0, 0));

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let colors = generator.generate_layer_colors_by_led(0).unwrap();

        // Key at LED 0 should use layer default (blue) since no category or override
        assert_eq!(colors[0], RgbColor::new(0, 0, 255));

        // Key at LED 1 should use override (red) - highest priority
        assert_eq!(colors[1], RgbColor::new(255, 0, 0));
    }

    #[test]
    fn test_keymap_c_includes_rgb_table_when_rgb_enabled() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Add category to trigger custom colors
        let category = crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
        layout.add_category(category).unwrap();

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let keymap_c = generator.generate_keymap_c().unwrap();

        // Should include RGB matrix color table
        assert!(keymap_c.contains("#ifdef RGB_MATRIX_ENABLE"));
        assert!(keymap_c.contains("layer_base_colors"));
        assert!(keymap_c.contains("layer_base_colors_layer_count"));
    }

    #[test]
    fn test_config_h_sets_tui_layer_colors_mode() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Add category to trigger custom colors
        let category = crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
        layout.add_category(category).unwrap();

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let config_h = generator.generate_merged_config_h().unwrap();

        // Should set the TUI layer colors mode as default
        assert!(config_h.contains("RGB_MATRIX_TUI_LAYER_COLORS"));
        assert!(config_h.contains("#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS"));
        assert!(config_h.contains("LAYER_BASE_COLORS_LAYER_COUNT 1"));
    }

    #[test]
    fn test_multi_layer_color_table_generation() {
        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Layer 0: White default
        // Layer 1: Red default
        let mut layer1 = Layer::new(1, "Red Layer", RgbColor::new(255, 0, 0)).unwrap();
        layer1.add_key(KeyDefinition::new(Position::new(0, 0), "KC_1"));
        layer1.add_key(KeyDefinition::new(Position::new(0, 1), "KC_2"));
        layout.add_layer(layer1).unwrap();

        // Layer 2: Green default
        let mut layer2 = Layer::new(2, "Green Layer", RgbColor::new(0, 255, 0)).unwrap();
        layer2.add_key(KeyDefinition::new(Position::new(0, 0), "KC_3"));
        layer2.add_key(KeyDefinition::new(Position::new(0, 1), "KC_4"));
        layout.add_layer(layer2).unwrap();

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let color_table = generator.generate_rgb_matrix_color_table().unwrap();

        // Verify 3 layers
        assert!(color_table.contains("layer_base_colors[3][2][3]"));
        assert!(color_table.contains("layer_base_colors_layer_count = 3;"));

        // Verify each layer's colors are present
        assert!(color_table.contains("{255, 255, 255}")); // White
        assert!(color_table.contains("{255,   0,   0}")); // Red
        assert!(color_table.contains("{  0, 255,   0}")); // Green
    }

    #[test]
    fn test_config_h_emits_tap_hold_settings() {
        use crate::models::{TapHoldPreset, TapHoldSettings};

        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Apply HomeRowMods preset
        layout.tap_hold_settings = TapHoldSettings::from_preset(TapHoldPreset::HomeRowMods);

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let config_h = generator.generate_merged_config_h().unwrap();

        // Verify tap-hold settings are emitted
        assert!(config_h.contains("// Tap-Hold Configuration"));
        assert!(config_h.contains("#define TAPPING_TERM 175"));
        assert!(config_h.contains("#define QUICK_TAP_TERM 120"));
        assert!(config_h.contains("#define PERMISSIVE_HOLD"));
        assert!(config_h.contains("#define RETRO_TAPPING"));
        assert!(config_h.contains("#define FLOW_TAP_TERM 150"));
        assert!(config_h.contains("#define CHORDAL_HOLD"));
    }

    #[test]
    fn test_config_h_does_not_emit_default_tap_hold() {
        let (layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Layout has default tap-hold settings
        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let config_h = generator.generate_merged_config_h().unwrap();

        // Should NOT contain tap-hold defines
        assert!(!config_h.contains("TAPPING_TERM"));
        assert!(!config_h.contains("QUICK_TAP_TERM"));
        assert!(!config_h.contains("PERMISSIVE_HOLD"));
        assert!(!config_h.contains("RETRO_TAPPING"));
    }

    #[test]
    fn test_config_h_emits_hold_on_other_key_press() {
        use crate::models::{HoldDecisionMode, TapHoldSettings};

        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Set up custom tap-hold settings with HoldOnOtherKeyPress
        layout.tap_hold_settings = TapHoldSettings {
            tapping_term: 150,
            hold_mode: HoldDecisionMode::HoldOnOtherKeyPress,
            ..TapHoldSettings::default()
        };

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let config_h = generator.generate_merged_config_h().unwrap();

        assert!(config_h.contains("#define TAPPING_TERM 150"));
        assert!(config_h.contains("#define HOLD_ON_OTHER_KEY_PRESS"));
        assert!(!config_h.contains("PERMISSIVE_HOLD"));
    }

    #[test]
    fn test_config_h_emits_tapping_toggle() {
        use crate::models::TapHoldSettings;

        let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

        // Change tapping toggle from default (5) to 3
        layout.tap_hold_settings = TapHoldSettings {
            tapping_toggle: 3,
            ..TapHoldSettings::default()
        };

        let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
        let config_h = generator.generate_merged_config_h().unwrap();

        assert!(config_h.contains("#define TAPPING_TOGGLE 3"));
    }
}
