//! Generation Tests
//!
//! Tests that firmware keymap.c and config.h files are generated
//! correctly, including structure, LED ordering, categories,
//! atomic writes, and the full validation-to-generation pipeline.

use super::helpers::*;
use lazyqmk::firmware::{FirmwareGenerator, FirmwareValidator};
use lazyqmk::keycode_db::KeycodeDb;
use std::fs;
use std::path::PathBuf;

#[test]
fn test_generation_creates_files() {
    // Arrange
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let layout = create_test_layout();
    let geometry = create_test_geometry();
    let mapping = create_test_mapping();
    let config = create_test_config(&temp_dir);

    let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

    // Act
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let result = generator.generate();

    // Assert
    assert!(
        result.is_ok(),
        "Generation should succeed: {:?}",
        result.err()
    );

    let (keymap_path, _) = result.unwrap();
    assert!(
        PathBuf::from(&keymap_path).exists(),
        "keymap.c should be created"
    );
}

#[test]
fn test_generation_keymap_c_structure() {
    // Arrange
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let layout = create_test_layout();
    let geometry = create_test_geometry();
    let mapping = create_test_mapping();
    let config = create_test_config(&temp_dir);

    let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

    // Act
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let result = generator.generate();
    assert!(result.is_ok(), "Generation should succeed");

    let (keymap_path, _) = result.unwrap();
    let content = fs::read_to_string(&keymap_path).expect("Should be able to read keymap.c");

    // Assert - Check for expected C code structure
    assert!(
        content.contains("// Generated by lazyqmk"),
        "Should have generator comment"
    );
    assert!(
        content.contains("const uint16_t PROGMEM keymaps"),
        "Should have PROGMEM keymaps array"
    );
    assert!(
        content.contains("LAYOUT_test"),
        "Should use correct layout macro"
    );
    assert!(
        content.contains("KC_0"),
        "Should contain keycodes from layer 0"
    );
    assert!(
        content.contains("KC_TRNS"),
        "Should contain transparent keycodes from layer 1"
    );

    // Check for layer comments
    assert!(
        content.contains("// Layer 0: Base"),
        "Should have layer 0 comment"
    );
    assert!(
        content.contains("// Layer 1: Function"),
        "Should have layer 1 comment"
    );
}

#[test]
fn test_generation_led_ordering() {
    // Arrange
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let layout = create_test_layout();
    let geometry = create_test_geometry();
    let mapping = create_test_mapping();
    let config = create_test_config(&temp_dir);

    let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

    // Act
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let result = generator.generate();
    assert!(result.is_ok(), "Generation should succeed");

    let (keymap_path, _) = result.unwrap();
    let content = fs::read_to_string(&keymap_path).expect("Should be able to read keymap.c");

    // Assert - Keys should be ordered by LED index (0, 1, 2, 3, 4, 5)
    // Find the first LAYOUT_test macro in Layer 0
    let layer0_start = content
        .find("// Layer 0: Base")
        .expect("Should find Layer 0 comment");
    let layer0_layout = &content[layer0_start..];
    let layout_start = layer0_layout
        .find("LAYOUT_test(")
        .expect("Should find LAYOUT_test macro");
    let layout_section = &layer0_layout[layout_start..];

    // Keys should appear in LED order: KC_0, KC_1, KC_2, KC_3, KC_4, KC_5
    let kc0_pos = layout_section.find("KC_0").expect("Should find KC_0");
    let kc1_pos = layout_section.find("KC_1").expect("Should find KC_1");
    let kc2_pos = layout_section.find("KC_2").expect("Should find KC_2");
    let kc5_pos = layout_section.find("KC_5").expect("Should find KC_5");

    assert!(kc0_pos < kc1_pos, "KC_0 should appear before KC_1");
    assert!(kc1_pos < kc2_pos, "KC_1 should appear before KC_2");
    assert!(kc2_pos < kc5_pos, "KC_2 should appear before KC_5");
}

#[test]
fn test_generation_with_categories() {
    // Arrange
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let mut layout = create_test_layout();

    // Add a category
    let nav_category = lazyqmk::models::Category::new(
        "navigation",
        "Navigation",
        lazyqmk::models::RgbColor::new(0, 255, 0),
    )
    .expect("Should create category");

    layout.categories.push(nav_category);
    layout.layers[0].keys[0].category_id = Some("navigation".to_string());

    let geometry = create_test_geometry();
    let mapping = create_test_mapping();
    let config = create_test_config(&temp_dir);

    let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

    // Act
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let result = generator.generate();

    // Assert
    assert!(result.is_ok(), "Generation with categories should succeed");

    let (keymap_path, _) = result.unwrap();
    let content = fs::read_to_string(&keymap_path).expect("Should be able to read keymap.c");

    // Categories don't affect C code generation, but should not cause errors
    assert!(content.contains("KC_0"), "Should still contain keycodes");
}

#[test]
fn test_generation_atomic_write() {
    // Arrange
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let layout = create_test_layout();
    let geometry = create_test_geometry();
    let mapping = create_test_mapping();
    let config = create_test_config(&temp_dir);
    let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

    // Act - Generate twice to test atomic write (temp + rename)
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let result1 = generator.generate();
    assert!(result1.is_ok(), "First generation should succeed");

    let result2 = generator.generate();
    assert!(
        result2.is_ok(),
        "Second generation should succeed (overwrite)"
    );

    // Assert - Files should exist and be readable
    let (keymap_path, _) = result2.unwrap();
    let keymap_content =
        fs::read_to_string(&keymap_path).expect("Should read keymap.c after overwrite");

    assert!(!keymap_content.is_empty(), "keymap.c should not be empty");
}

#[test]
fn test_full_pipeline_validation_to_generation() {
    // Arrange
    let temp_dir = TempDir::new().expect("Failed to create temp dir");
    let layout = create_test_layout();
    let geometry = create_test_geometry();
    let mapping = create_test_mapping();
    let config = create_test_config(&temp_dir);
    let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

    // Act - Full pipeline: Validate then Generate

    // Step 1: Validate
    let validator = FirmwareValidator::new(&layout, &geometry, &mapping, &keycode_db);
    let report = validator.validate().expect("Validation should complete");
    assert!(
        report.is_valid(),
        "Layout should be valid before generation"
    );

    // Step 2: Generate
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let result = generator.generate();

    // Assert
    assert!(
        result.is_ok(),
        "Generation should succeed after validation: {:?}",
        result.err()
    );

    let (keymap_path, _) = result.unwrap();
    assert!(
        PathBuf::from(&keymap_path).exists(),
        "keymap.c should exist"
    );

    // Verify file contents are non-empty and valid
    let keymap_content = fs::read_to_string(&keymap_path).unwrap();

    assert!(
        keymap_content.len() > 100,
        "keymap.c should have substantial content"
    );
}
