// Generated by lazyqmk
// Layout: Test Layout
// Keyboard: test_keyboard
// Layout Variant: LAYOUT_test

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Layer 0: Base
[0] = LAYOUT_test(KC_0, KC_1, KC_2, KC_3, KC_4, KC_5),
    // Layer 1: Function
[1] = LAYOUT_test(KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5)
};

#ifdef ENCODER_MAP_ENABLE
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = {
    },
    [1] = {
    },
};
#endif

#ifdef RGB_MATRIX_ENABLE
const uint8_t PROGMEM layer_base_colors[2][6][3] = {
    {
        {255, 255, 255},
        {255, 255, 255},
        {255, 255, 255},
        {255, 255, 255},
        {255, 255, 255},
        {255, 255, 255}
    },
    {
        {100, 100, 255},
        {100, 100, 255},
        {100, 100, 255},
        {100, 100, 255},
        {100, 100, 255},
        {100, 100, 255}
    }
};
const uint8_t PROGMEM layer_base_colors_layer_count = 2;
#endif

// Bootloader combo: Q+R (left) or U+P (right) held for 1500ms
static uint32_t bootloader_combo_timer = 0;
static bool bootloader_combo_active = false;

#ifdef RGB_MATRIX_ENABLE
#ifdef LQMK_IDLE_TIMEOUT_MS

// Idle Effect State Machine
typedef enum {
    IDLE_STATE_ACTIVE,
    IDLE_STATE_IDLE_EFFECT,
    IDLE_STATE_OFF
} idle_state_t;

static idle_state_t idle_state = IDLE_STATE_ACTIVE;
static uint32_t last_activity_time = 0;

void matrix_scan_user(void) {
    uint32_t elapsed = timer_elapsed32(last_activity_time);

    switch (idle_state) {
        case IDLE_STATE_ACTIVE:
            if (elapsed >= LQMK_IDLE_TIMEOUT_MS) {
                // Transition to idle effect
                rgb_matrix_mode_noeeprom(LQMK_IDLE_EFFECT_MODE);
                idle_state = IDLE_STATE_IDLE_EFFECT;
            }
            break;

        case IDLE_STATE_IDLE_EFFECT:
            if (elapsed >= LQMK_IDLE_TIMEOUT_MS + LQMK_IDLE_EFFECT_DURATION_MS) {
                // Transition to off
                rgb_matrix_disable_noeeprom();
                idle_state = IDLE_STATE_OFF;
            }
            break;

        case IDLE_STATE_OFF:
            // Stay off until activity
            break;
    }
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    // Bootloader combo: Q+R (left) or U+P (right) held for 1500ms
    {
        // Resolve the basic keycode (handle LT/MT/MOD wrappers)
        uint16_t base_kc = keycode;
        if (IS_QK_MODS(keycode)) {
            base_kc = QK_MODS_GET_BASIC_KEYCODE(keycode);
        } else if (IS_QK_LAYER_TAP(keycode)) {
            base_kc = QK_LAYER_TAP_GET_TAP_KEYCODE(keycode);
        } else if (IS_QK_MOD_TAP(keycode)) {
            base_kc = QK_MOD_TAP_GET_TAP_KEYCODE(keycode);
        }
        bool is_combo_key = (base_kc == KC_Q || base_kc == KC_R
                          || base_kc == KC_U || base_kc == KC_P);
        if (is_combo_key) {
            static bool q_held = false;
            static bool r_held = false;
            static bool u_held = false;
            static bool p_held = false;

            if (record->event.pressed) {
                if (base_kc == KC_Q) q_held = true;
                if (base_kc == KC_R) r_held = true;
                if (base_kc == KC_U) u_held = true;
                if (base_kc == KC_P) p_held = true;
            } else {
                if (base_kc == KC_Q) q_held = false;
                if (base_kc == KC_R) r_held = false;
                if (base_kc == KC_U) u_held = false;
                if (base_kc == KC_P) p_held = false;
            }

            // Check if either pair is complete
            bool pair_active = (q_held && r_held) || (u_held && p_held);
            if (pair_active) {
                if (!bootloader_combo_active) {
                    bootloader_combo_timer = timer_read32();
                    bootloader_combo_active = true;
                }
            } else {
                bootloader_combo_active = false;
            }
        }
    }

    if (record->event.pressed) {
        // Reset activity timer
        last_activity_time = timer_read32();

        if (idle_state != IDLE_STATE_ACTIVE) {
            // Re-enable RGB if it was disabled
            if (idle_state == IDLE_STATE_OFF) {
                rgb_matrix_enable_noeeprom();
            }

            // Restore TUI layer colors mode
            rgb_matrix_mode_noeeprom(RGB_MATRIX_TUI_LAYER_COLORS);
            idle_state = IDLE_STATE_ACTIVE;
        }
    }

    return true;
}

void keyboard_post_init_user(void) {
    last_activity_time = timer_read32();
}

#endif // LQMK_IDLE_TIMEOUT_MS
#endif // RGB_MATRIX_ENABLE



// Bootloader combo: check timer in housekeeping task
void housekeeping_task_user(void) {
    if (bootloader_combo_active && timer_elapsed32(bootloader_combo_timer) > 1500) {
        bootloader_jump();
    }
}