//! `config.h` generation.
//!
//! Merges keymap-specific `#define` flags (tap-hold, RGB matrix, idle effect,
//! PaletteFX, ripple overlay, combo count) with the keyboard's variant-specific
//! `keyboard.json` config. Note: `RGB_MATRIX_LED_COUNT` belongs in `keyboard.json`,
//! not in the keymap `config.h`.

use anyhow::Result;

use super::FirmwareGenerator;
use crate::constants::APP_BINARY_NAME;

/// Generates config.h for the keymap.
///
/// This generates a minimal keymap-specific config.h.
/// Note: `RGB_MATRIX_LED_COUNT` should be defined in the keyboard's variant-specific
/// keyboard.json file, not in the keymap config.h.
#[allow(clippy::cast_possible_truncation)]
pub fn generate(gen: &FirmwareGenerator) -> Result<String> {
    use crate::models::HoldDecisionMode;

    let mut content = String::new();

    // Add our generated configuration
    content.push_str(&format!("// Generated by {}\n", APP_BINARY_NAME));
    content.push_str(&format!("// Layout: {}\n", gen.layout.metadata.name));
    content.push_str(&format!(
        "// Generated: {}\n",
        chrono::Local::now().format("%Y-%m-%d %H:%M:%S")
    ));
    content.push('\n');
    content.push_str("#pragma once\n");
    content.push('\n');
    content.push_str("// Add keymap-specific configuration here\n");

    // === Tap-Hold Settings ===
    let ths = &gen.layout.tap_hold_settings;

    // Validate tap-hold settings before generating
    ths.validate()?;

    // Only emit non-default tap-hold settings
    if ths.has_custom_settings() {
        content.push_str("\n// Tap-Hold Configuration\n");

        // Tapping Term
        if ths.has_custom_tapping_term() {
            content.push_str(&format!("#define TAPPING_TERM {}\n", ths.tapping_term));
        }

        // Quick Tap Term
        if ths.has_custom_quick_tap_term() {
            if let Some(term) = ths.quick_tap_term {
                content.push_str(&format!("#define QUICK_TAP_TERM {term}\n"));
            }
            // None means use TAPPING_TERM (QMK default), no need to emit
        }

        // Hold Mode - use config_define() to get the #define name
        if ths.hold_mode != HoldDecisionMode::Default {
            if let Some(define_name) = ths.hold_mode.config_define() {
                content.push_str(&format!("#define {define_name}\n"));
            }
        }

        // Retro Tapping - only emit if enabled
        if ths.retro_tapping {
            content.push_str("#define RETRO_TAPPING\n");
        }

        // Tapping Toggle - only emit if different from default (5)
        if ths.tapping_toggle != 5 {
            content.push_str(&format!("#define TAPPING_TOGGLE {}\n", ths.tapping_toggle));
        }

        // Flow Tap Term (QMK 0.26+)
        if let Some(term) = ths.flow_tap_term {
            content.push_str(&format!("#define FLOW_TAP_TERM {term}\n"));
        }

        // Chordal Hold (QMK 0.26+) - only emit if enabled
        if ths.chordal_hold {
            content.push_str("#define CHORDAL_HOLD\n");
        }
    }

    // === RGB Settings ===
    // RGB Matrix brightness (0-255, converted from 0-100%)
    let brightness_255 = (u16::from(gen.layout.rgb_brightness.as_percent()) * 255 / 100) as u8;
    if brightness_255 < 255 {
        content.push_str("\n// RGB Matrix Maximum Brightness\n");
        content.push_str(&format!(
            "#define RGB_MATRIX_MAXIMUM_BRIGHTNESS {}\n",
            brightness_255
        ));
    }

    // RGB Matrix default speed (0-255)
    if gen.layout.rgb_matrix_default_speed != 127 {
        content.push_str("\n// RGB Matrix Default Animation Speed\n");
        content.push_str(&format!(
            "#define RGB_MATRIX_DEFAULT_SPD {}\n",
            gen.layout.rgb_matrix_default_speed
        ));
    }

    // === Idle Effect Settings ===
    // When idle effect is enabled, we use a custom state machine instead of RGB_MATRIX_TIMEOUT
    // When PaletteFX is enabled, the idle effect uses the PaletteFX default effect
    // as the screensaver animation, rather than a standard RGB effect.
    let idle_settings = &gen.layout.idle_effect_settings;
    let palette_fx = &gen.layout.palette_fx;
    if idle_settings.enabled && gen.geometry.has_rgb_matrix() {
        content.push_str("\n// Idle Effect Configuration\n");
        content.push_str(&format!(
            "#define LQMK_IDLE_TIMEOUT_MS {}\n",
            idle_settings.idle_timeout_ms
        ));
        content.push_str(&format!(
            "#define LQMK_IDLE_EFFECT_DURATION_MS {}\n",
            idle_settings.idle_effect_duration_ms
        ));
        // When PaletteFX is enabled, use its effect as the idle screensaver animation
        if palette_fx.enabled {
            content.push_str(&format!(
                "#define LQMK_IDLE_EFFECT_MODE {}\n",
                palette_fx.default_effect.qmk_mode_name()
            ));
        } else {
            content.push_str(&format!(
                "#define LQMK_IDLE_EFFECT_MODE {}\n",
                idle_settings.idle_effect_mode.qmk_mode_name()
            ));
        }
    } else {
        // RGB Matrix timeout (auto-off after inactivity) - only when idle effect is disabled
        if gen.layout.rgb_timeout_ms > 0 {
            content.push_str("\n// RGB Matrix Timeout (auto-off after inactivity)\n");
            content.push_str(&format!(
                "#define RGB_MATRIX_TIMEOUT {}\n",
                gen.layout.rgb_timeout_ms
            ));
        }
    }

    // If the keyboard has RGB matrix, set the default mode.
    // PaletteFX effects are ONLY used as idle screensaver, never as the default mode.
    // The default mode is always TUI_LAYER_COLORS when custom colors are configured.
    if gen.geometry.has_rgb_matrix() && gen.layout_has_custom_colors() {
        content.push_str("\n// Default to TUI layer-aware RGB colors when available\n");
        content.push_str("#ifdef RGB_MATRIX_ENABLE\n");
        content.push_str("#    undef RGB_MATRIX_DEFAULT_MODE\n");
        content.push_str("#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS\n");
        content.push_str("#    define LAYER_BASE_COLORS_LAYER_COUNT ");
        content.push_str(&format!("{}\n", gen.layout.layers.len()));
        content.push_str("#endif\n");
    }

    // === PaletteFX Module Settings ===
    // PaletteFX effects are used as idle screensaver animations.
    // The PALETTEFX_ENABLE_* defines tell the module which effects/palettes
    // to compile into the firmware.
    let palette_fx = &gen.layout.palette_fx;
    if palette_fx.enabled && gen.geometry.has_rgb_matrix() {
        content.push_str("\n// PaletteFX Community Module Configuration\n");
        content.push_str("// Note: PaletteFX runs as idle screensaver, not as default mode.\n");
        content
            .push_str("// The idle effect state machine uses LQMK_IDLE_EFFECT_MODE (see above)\n");
        content.push_str("// which is set to the PaletteFX default effect at compile time.\n");
        content.push_str("#ifdef RGB_MATRIX_ENABLE\n");

        // Enable all effects or individual effects
        if palette_fx.enable_all_effects {
            content.push_str("#    define PALETTEFX_ENABLE_ALL_EFFECTS\n");
        } else {
            content.push_str(&format!(
                "#    define {}\n",
                palette_fx.default_effect.enable_define()
            ));
        }

        // Enable all palettes or individual palette
        if palette_fx.enable_all_palettes {
            content.push_str("#    define PALETTEFX_ENABLE_ALL_PALETTES\n");
        } else {
            content.push_str(&format!(
                "#    define {}\n",
                palette_fx.default_palette.enable_define()
            ));
        }

        content.push_str("#endif // RGB_MATRIX_ENABLE\n");
    }

    // === RGB Overlay Ripple Settings ===
    // Key-action ripple overlay runs independently of PaletteFX.
    // PaletteFX is only used as an idle screensaver, never as a replacement
    // for key-triggered effects.
    let ripple_settings = &gen.layout.rgb_overlay_ripple;
    if ripple_settings.enabled && gen.geometry.has_rgb_matrix() {
        // Validate settings before generating
        ripple_settings.validate()?;

        content.push_str("\n// RGB Overlay Ripple Configuration\n");
        content.push_str("#define LQMK_RIPPLE_OVERLAY_ENABLED\n");
        content.push_str(&format!(
            "#define LQMK_RIPPLE_MAX_RIPPLES {}\n",
            ripple_settings.max_ripples
        ));
        content.push_str(&format!(
            "#define LQMK_RIPPLE_DURATION_MS {}\n",
            ripple_settings.duration_ms
        ));
        content.push_str(&format!(
            "#define LQMK_RIPPLE_SPEED {}\n",
            ripple_settings.speed
        ));
        content.push_str(&format!(
            "#define LQMK_RIPPLE_BAND_WIDTH {}\n",
            ripple_settings.band_width
        ));
        content.push_str(&format!(
            "#define LQMK_RIPPLE_AMPLITUDE_PCT {}\n",
            ripple_settings.amplitude_pct
        ));
        // Maximum wavefront radius in matrix-space distance.
        // This controls how far the ripple expands outward from the key.
        // Use amplitude_pct (0-100) mapped to 2..=6 matrix units.
        let max_radius = 2 + (u16::from(ripple_settings.amplitude_pct) * 4 / 100);
        content.push_str(&format!("#define LQMK_RIPPLE_MAX_RADIUS {max_radius}\n"));
        // Fade width: controls gradient softness. Proportional to max radius
        // so the pulse is always narrower than the total span (visible movement).
        let fade_width = (max_radius / 2).clamp(1, 4) as u8;
        content.push_str(&format!("#define LQMK_RIPPLE_FADE_WIDTH {fade_width}\n"));
        // Scaled duration for speed-aware radius calculation.
        // Speed acts as a multiplier on expansion rate.
        // At default speed=200, LQMK_RIPPLE_SCALED_DURATION = duration_ms * 200.
        // The radius formula is: (elapsed * max_radius * speed) / scaled_duration
        // which simplifies to (elapsed * max_radius) / duration at speed=200.
        let scaled_duration = u32::from(ripple_settings.duration_ms).saturating_mul(200);
        content.push_str(&format!(
            "#define LQMK_RIPPLE_SCALED_DURATION {scaled_duration}UL\n"
        ));
        // Amplitude envelope scale factor for scale16by8.
        // Gives a triangular 0→255→0 ramp over the ripple duration.
        // Pre-computed so the integer math doesn't collapse to zero.
        let half_duration = u32::from(ripple_settings.duration_ms / 2);
        // amp_scale: pre-computed divisor so `(effective_elapsed * 2) * amp_scale`
        // produces a 0→255→0 triangle over the ripple duration without collapsing
        // to zero for very small durations. Default to 255 if half_duration is 0
        // (which validate() above should have rejected, but we guard here).
        let amp_scale = half_duration
            .checked_div(255u32 * 256)
            .map(|v| v.min(255) as u8)
            .unwrap_or(255);
        content.push_str(&format!("#define LQMK_RIPPLE_AMP_SCALE {amp_scale}\n"));
        content.push_str(&format!(
            "#define LQMK_RIPPLE_TRIGGER_ON_PRESS {}\n",
            if ripple_settings.trigger_on_press {
                "1"
            } else {
                "0"
            }
        ));
        content.push_str(&format!(
            "#define LQMK_RIPPLE_TRIGGER_ON_RELEASE {}\n",
            if ripple_settings.trigger_on_release {
                "1"
            } else {
                "0"
            }
        ));
        // Multi-wave: number of concentric waves per keypress
        content.push_str(&format!(
            "#define LQMK_RIPPLE_WAVE_COUNT {}\n",
            ripple_settings.wave_count
        ));
        // Delay between consecutive waves (ms)
        content.push_str(&format!(
            "#define LQMK_RIPPLE_WAVE_DELAY_MS {}\n",
            ripple_settings.wave_delay_ms
        ));
    }

    // === Combo Settings ===
    let real_combo_count = gen
        .layout
        .combo_settings
        .combos
        .iter()
        .filter(|c| !c.placeholder)
        .count();
    if gen.layout.combo_settings.enabled && real_combo_count > 0 {
        content.push_str("\n// Combo Configuration\n");
        // COMBO_ENABLE is set via rules.mk (COMBO_ENABLE = yes) which causes QMK's
        // build system to pass -DCOMBO_ENABLE and include process_combo.c.
        // Defining it again here would cause a "redefined" compiler error.
        content.push_str(&format!("#define COMBO_COUNT {}\n", real_combo_count));
    }

    Ok(content)
}
