//! Firmware generation for QMK keymap.c and config.h.
//!
//! This module generates QMK C code from keyboard layouts using the LED index order.
//! Works with standard QMK firmware (not Vial fork).
//!
//! The module is split across several files:
//! - `keymap_helpers` — header detection, layer-key resolution, color tables
//! - `encoder`        — conditional encoder_map
//! - `idle`           — idle effect state machine
//! - `ripple`         — RGB overlay ripple (key-action effect)
//! - `combo`          — two-key combo code
//! - `tap_dance`      — tap dance enum, helpers, actions
//! - `config_h`       — merged config.h emission
//! - `rules_mk`       — rules.mk + keymap.json
//! - `tests`          — 47 inline tests for the generator

// Allow format! appended to String - more readable than write! in code generation
#![allow(clippy::format_push_string)]

mod combo;
mod config_h;
mod encoder;
mod idle;
mod keymap_helpers;
mod ripple;
mod rules_mk;
mod tap_dance;

#[cfg(test)]
mod tests;

use crate::config::Config;
use crate::constants::APP_BINARY_NAME;
use crate::keycode_db::KeycodeDb;
use crate::models::keyboard_geometry::KeyboardGeometry;
use crate::models::layout::Layout;
use crate::models::visual_layout_mapping::VisualLayoutMapping;
use anyhow::{Context, Result};
use std::fs;

/// Firmware generator for keymap.c and config.h.
pub struct FirmwareGenerator<'a> {
    pub(crate) layout: &'a Layout,
    pub(crate) geometry: &'a KeyboardGeometry,
    pub(crate) mapping: &'a VisualLayoutMapping,
    pub(crate) config: &'a Config,
    pub(crate) keycode_db: &'a KeycodeDb,
}

impl<'a> FirmwareGenerator<'a> {
    /// Creates a new firmware generator.
    #[must_use]
    pub const fn new(
        layout: &'a Layout,
        geometry: &'a KeyboardGeometry,
        mapping: &'a VisualLayoutMapping,
        config: &'a Config,
        keycode_db: &'a KeycodeDb,
    ) -> Self {
        Self {
            layout,
            geometry,
            mapping,
            config,
            keycode_db,
        }
    }

    /// Generates keymap.c, config.h, and rules.mk files.
    ///
    /// Files are written to both:
    /// 1. Timestamped output directory (for archival)
    /// 2. QMK keymap directory (for building)
    ///
    /// Returns paths to the generated files in the timestamped directory:
    /// (`keymap_path`, `config_h_path`)
    pub fn generate(&self) -> Result<(String, String)> {
        // Create timestamped output directory
        let timestamp_dir = self.create_timestamped_output_dir()?;

        // Generate config.h (merge with keyboard config if exists)
        let config_h = config_h::generate(self)?;
        let config_h_path = self.write_file_to_both(&timestamp_dir, "config.h", &config_h)?;

        // Generate keymap.c
        let keymap_c = self.generate_keymap_c()?;
        let keymap_path = self.write_file_to_both(&timestamp_dir, "keymap.c", &keymap_c)?;

        // Generate rules.mk (only written if features need enabling)
        let rules_mk = self.generate_rules_mk();
        if !rules_mk.is_empty() {
            self.write_file_to_both(&timestamp_dir, "rules.mk", &rules_mk)?;
        }

        // Generate keymap.json (for QMK community modules like PaletteFX)
        let keymap_json = self.generate_keymap_json();
        if !keymap_json.is_empty() {
            self.write_file_to_both(&timestamp_dir, "keymap.json", &keymap_json)?;
        }

        Ok((keymap_path, config_h_path))
    }

    /// Generates keymap.c C code.
    ///
    /// Creates a QMK keymap file with PROGMEM arrays for each layer.
    /// Keys are ordered by LED index as required by QMK.
    pub fn generate_keymap_c(&self) -> Result<String> {
        let mut code = String::new();

        // File header
        code.push_str(&format!("// Generated by {}\n", APP_BINARY_NAME));
        code.push_str(&format!("// Layout: {}\n", self.layout.metadata.name));
        code.push_str(&format!(
            "// Keyboard: {}\n",
            self.layout
                .metadata
                .keyboard
                .as_deref()
                .unwrap_or("unknown")
        ));
        code.push_str(&format!(
            "// Layout Variant: {}\n",
            self.layout
                .metadata
                .layout_variant
                .as_deref()
                .unwrap_or("unknown")
        ));
        code.push('\n');

        // Includes
        code.push_str("#include QMK_KEYBOARD_H\n");

        // Add language-specific keycode headers if needed
        let required_headers = self.detect_required_headers();
        for header in &required_headers {
            code.push_str(&format!("#include \"{}\"\n", header));
        }

        // Tap dance requires process_tap_dance.h definitions
        if !self.layout.tap_dances.is_empty() {
            code.push_str("#include \"process_keycode/process_tap_dance.h\"\n");
        }

        // lib8tion provides fast integer math (scale8, sin8, cos8, sqrt16, etc.)
        // Needed by reactive key-action overlay and PaletteFX community module.
        let needs_lib8tion = self.layout.rgb_overlay_ripple.enabled
            && self.geometry.has_rgb_matrix()
            || self.layout.palette_fx.enabled;
        if needs_lib8tion {
            code.push_str("#include <lib/lib8tion/lib8tion.h>\n");
        }

        code.push('\n');

        // Add tap dance configuration if any tap dances are defined
        if !self.layout.tap_dances.is_empty() {
            code.push_str("// Tap Dance Configuration\n");
            code.push_str(&self.generate_tap_dance_enum());
            code.push('\n');
            code.push_str(&self.generate_tap_dance_helpers());
            if !self.generate_tap_dance_helpers().is_empty() {
                code.push('\n');
            }
            code.push_str(&self.generate_tap_dance_actions());
            code.push('\n');
        }

        // Keymap definition
        code.push_str("const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {\n");

        // Generate each layer
        for (layer_idx, layer) in self.layout.layers.iter().enumerate() {
            code.push_str(&format!("    // Layer {}: {}\n", layer_idx, layer.name));
            code.push_str(&format!(
                "[{}] = {}(",
                layer_idx,
                self.layout
                    .metadata
                    .layout_variant
                    .as_deref()
                    .unwrap_or("LAYOUT")
            ));

            // Generate keys in layout order (matches info.json layout array)
            let keys_by_layout = self.generate_layer_keys_by_layout(layer)?;

            // Format keys (wrap at reasonable line length)
            let keys_str = keys_by_layout.join(", ");
            if keys_str.len() > 80 {
                // Multi-line formatting
                code.push_str("\n        ");
                for (idx, keycode) in keys_by_layout.iter().enumerate() {
                    code.push_str(keycode);
                    if idx < keys_by_layout.len() - 1 {
                        code.push_str(", ");
                    }
                    // Line wrap every 6 keys
                    if (idx + 1) % 6 == 0 && idx < keys_by_layout.len() - 1 {
                        code.push_str("\n        ");
                    }
                }
                code.push_str("\n    ");
            } else {
                // Single line formatting
                code.push_str(&keys_str);
            }

            code.push(')');
            if layer_idx < self.layout.layers.len() - 1 {
                code.push_str(",\n");
            } else {
                code.push('\n');
            }
        }

        code.push_str("};\n");

        // Add conditional encoder_map (only when ENCODER_MAP_ENABLE is defined)
        code.push('\n');
        code.push_str(&self.generate_conditional_encoder_map()?);

        // Add optional RGB matrix base color table when RGB is present.
        code.push('\n');
        code.push_str(&self.generate_rgb_matrix_color_table()?);

        // Add idle effect state machine code if enabled
        code.push('\n');
        code.push_str(&self.generate_idle_effect_code()?);

        // Add RGB overlay ripple code if enabled
        code.push('\n');
        code.push_str(&self.generate_ripple_overlay_code()?);

        // Add combo code if enabled
        code.push('\n');
        code.push_str(&self.generate_combo_code()?);

        // Bootloader combo timer check (runs independently of idle/ripple)
        code.push('\n');
        code.push_str("// Bootloader combo: check timer in housekeeping task\n");
        code.push_str("void housekeeping_task_user(void) {\n");
        code.push_str("    if (bootloader_combo_active && timer_elapsed32(bootloader_combo_timer) > 1500) {\n");
        code.push_str("        bootloader_jump();\n");
        code.push_str("    }\n");
        code.push_str("}\n");

        Ok(code)
    }

    // === Small helpers (stay in mod.rs) ===

    /// Scans all keycodes in the layout and returns the set of additional
    /// header files that need to be included for language-specific keycodes.
    pub fn detect_required_headers(&self) -> Vec<String> {
        keymap_helpers::detect_required_headers(self)
    }

    /// Generates keycodes for a layer ordered by layout index.
    pub fn generate_layer_keys_by_layout(
        &self,
        layer: &crate::models::layer::Layer,
    ) -> Result<Vec<String>> {
        keymap_helpers::generate_layer_keys_by_layout(self, layer)
    }

    /// Generates resolved colors for a layer ordered by LED index.
    pub fn generate_layer_colors_by_led(
        &self,
        layer_idx: usize,
    ) -> Result<Vec<crate::models::RgbColor>> {
        keymap_helpers::generate_layer_colors_by_led(self, layer_idx)
    }

    /// Returns true if the layout uses any custom color semantics.
    pub fn layout_has_custom_colors(&self) -> bool {
        keymap_helpers::layout_has_custom_colors(self)
    }

    /// Generates an RGB matrix base color table in C when RGB is present.
    pub fn generate_rgb_matrix_color_table(&self) -> Result<String> {
        keymap_helpers::generate_rgb_matrix_color_table(self)
    }

    // === Mega-function delegators (delegate to free functions in submodules) ===

    /// Generates conditional encoder_map code.
    pub fn generate_conditional_encoder_map(&self) -> Result<String> {
        encoder::generate(self)
    }

    /// Generates idle effect state machine code if enabled.
    pub fn generate_idle_effect_code(&self) -> Result<String> {
        idle::generate(self)
    }

    /// Generates RGB overlay ripple code if enabled.
    pub fn generate_ripple_overlay_code(&self) -> Result<String> {
        ripple::generate(self)
    }

    /// Generates combo code if enabled.
    pub fn generate_combo_code(&self) -> Result<String> {
        combo::generate(self)
    }

    /// Generates tap dance enum definition.
    pub fn generate_tap_dance_enum(&self) -> String {
        tap_dance::generate_enum(self)
    }

    /// Generates helper functions for 3-way tap dances (with hold behavior).
    pub fn generate_tap_dance_helpers(&self) -> String {
        tap_dance::generate_helpers(self)
    }

    /// Generates tap dance actions array.
    pub fn generate_tap_dance_actions(&self) -> String {
        tap_dance::generate_actions(self)
    }

    /// Generates rules.mk for the keymap.
    #[must_use]
    pub fn generate_rules_mk(&self) -> String {
        rules_mk::generate_rules_mk(self)
    }

    /// Generates keymap.json for QMK community module support.
    pub fn generate_keymap_json(&self) -> String {
        rules_mk::generate_keymap_json(self)
    }

    /// Generates config.h for the keymap.
    pub fn generate_merged_config_h(&self) -> Result<String> {
        config_h::generate(self)
    }

    // === Output helpers (stay in mod.rs) ===

    /// Gets the keymap output directory.
    fn get_keymap_directory(&self) -> Result<std::path::PathBuf> {
        let qmk_path = self
            .config
            .paths
            .qmk_firmware
            .as_ref()
            .context("QMK firmware path not configured")?;

        // Use the keyboard path from layout metadata (which may include a variant)
        // E.g., "keebart/corne_choc_pro/standard" -> keyboards/keebart/corne_choc_pro/standard/keymaps/{keymap}
        let keyboard = self
            .layout
            .metadata
            .keyboard
            .as_deref()
            .context("Keyboard not set in layout metadata")?;
        let keymap = self
            .layout
            .metadata
            .keymap_name
            .as_deref()
            .context("Keymap name not set in layout metadata")?;

        let keymap_dir = qmk_path
            .join("keyboards")
            .join(keyboard)
            .join("keymaps")
            .join(keymap);

        // Create directory if it doesn't exist
        fs::create_dir_all(&keymap_dir)
            .with_context(|| format!("Failed to create directory {}", keymap_dir.display()))?;

        Ok(keymap_dir)
    }

    /// Creates a timestamped output directory for this build.
    fn create_timestamped_output_dir(&self) -> Result<std::path::PathBuf> {
        let timestamp = chrono::Local::now().format("%Y%m%d_%H%M%S");

        let keyboard = self
            .layout
            .metadata
            .keyboard
            .as_deref()
            .ok_or_else(|| anyhow::anyhow!("Keyboard not specified in layout metadata"))?;
        let keymap = self
            .layout
            .metadata
            .keymap_name
            .as_deref()
            .ok_or_else(|| anyhow::anyhow!("Keymap name not specified in layout metadata"))?;

        let dir_name = format!("{}_{}_{}", keyboard.replace('/', "_"), keymap, timestamp);

        let output_dir = self.config.build.output_dir.join(dir_name);

        fs::create_dir_all(&output_dir).with_context(|| {
            format!("Failed to create output directory {}", output_dir.display())
        })?;

        Ok(output_dir)
    }

    /// Writes a file to both the timestamped archive and the QMK keymap directory.
    fn write_file_to_both(
        &self,
        timestamp_dir: &std::path::Path,
        filename: &str,
        content: &str,
    ) -> Result<String> {
        // Write to timestamped archive directory
        let archive_path = timestamp_dir.join(filename);
        fs::write(&archive_path, content)
            .with_context(|| format!("Failed to write {}", archive_path.display()))?;

        // Write to QMK keymap directory
        let keymap_dir = self.get_keymap_directory()?;
        let qmk_path = keymap_dir.join(filename);
        fs::write(&qmk_path, content)
            .with_context(|| format!("Failed to write {}", qmk_path.display()))?;

        Ok(archive_path.display().to_string())
    }
}
