//! `rules.mk` and `keymap.json` generation.
//!
//! `rules.mk` enables QMK feature flags (`COMBO_ENABLE`, `TAP_DANCE_ENABLE`)
//! for the keymap build. `keymap.json` declares QMK community module
//! references (e.g. PaletteFX) when those features are enabled.
//!
//! A placeholder `rules.mk` is always emitted (when the keymap is otherwise
//! valid) so that re-deploying a keymap whose feature set shrinks (e.g. combos
//! are turned off after a previous combo-enabled deploy) overwrites any stale
//! `rules.mk` in the QMK keymap directory. Without the placeholder, a stale
//! `COMBO_ENABLE = yes` from a previous deploy could leak into the new build
//! and cause QMK's `keymap_introspection.c` to reference `key_combos` that the
//! freshly generated `keymap.c` no longer defines.

use crate::constants::APP_BINARY_NAME;

use super::FirmwareGenerator;

/// Generates rules.mk for the keymap.
///
/// QMK requires feature flags in `rules.mk` to include source files at build time.
/// Without these, `#define` flags in `config.h` alone cause linker errors like
/// `undefined reference to 'process_combo'`.
///
/// Always returns a non-empty string (a placeholder header when no features are
/// enabled) so the deploy step overwrites any stale `rules.mk` left behind by a
/// previous feature-enabled deployment. See the module-level docs for context.
#[must_use]
pub fn generate_rules_mk(gen: &FirmwareGenerator) -> String {
    let mut features: Vec<&str> = Vec::new();

    // Check for combos: enabled AND at least one non-placeholder combo
    let real_combo_count = gen
        .layout
        .combo_settings
        .combos
        .iter()
        .filter(|c| !c.placeholder)
        .count();
    if gen.layout.combo_settings.enabled && real_combo_count > 0 {
        features.push("COMBO_ENABLE = yes");
    }

    // Check for tap dances
    if !gen.layout.tap_dances.is_empty() {
        features.push("TAP_DANCE_ENABLE = yes");
    }

    let mut content = String::new();
    content.push_str(&format!("# Generated by {}\n", APP_BINARY_NAME));
    content.push('\n');
    if features.is_empty() {
        content.push_str("# No QMK features require explicit flags in this build.\n");
    } else {
        for feature in &features {
            content.push_str(feature);
            content.push('\n');
        }
    }

    content
}

/// Generates keymap.json for QMK community module support.
///
/// Currently only generates module references when `PaletteFX` is enabled.
/// Returns an empty string if no modules are needed.
pub fn generate_keymap_json(gen: &FirmwareGenerator) -> String {
    if !gen.layout.palette_fx.enabled {
        return String::new();
    }

    // Use serde_json to produce compact valid JSON
    let modules = serde_json::json!({
        "modules": ["getreuer/palettefx"]
    });

    serde_json::to_string_pretty(&modules).unwrap_or_default()
}
