//! `rules.mk` and `keymap.json` generation.
//!
//! `rules.mk` enables QMK feature flags (`COMBO_ENABLE`, `TAP_DANCE_ENABLE`)
//! for the keymap build. `keymap.json` declares QMK community module
//! references (e.g. PaletteFX) when those features are enabled.

use crate::constants::APP_BINARY_NAME;

use super::FirmwareGenerator;

/// Generates rules.mk for the keymap.
///
/// QMK requires feature flags in `rules.mk` to include source files at build time.
/// Without these, `#define` flags in `config.h` alone cause linker errors like
/// `undefined reference to 'process_combo'`.
///
/// Returns empty string if no features need enabling.
#[must_use]
pub fn generate_rules_mk(gen: &FirmwareGenerator) -> String {
    let mut features: Vec<&str> = Vec::new();

    // Check for combos: enabled AND at least one non-placeholder combo
    let real_combo_count = gen
        .layout
        .combo_settings
        .combos
        .iter()
        .filter(|c| !c.placeholder)
        .count();
    if gen.layout.combo_settings.enabled && real_combo_count > 0 {
        features.push("COMBO_ENABLE = yes");
    }

    // Check for tap dances
    if !gen.layout.tap_dances.is_empty() {
        features.push("TAP_DANCE_ENABLE = yes");
    }

    if features.is_empty() {
        return String::new();
    }

    let mut content = String::new();
    content.push_str(&format!("# Generated by {}\n", APP_BINARY_NAME));
    content.push('\n');
    for feature in &features {
        content.push_str(feature);
        content.push('\n');
    }

    content
}

/// Generates keymap.json for QMK community module support.
///
/// Currently only generates module references when `PaletteFX` is enabled.
/// Returns an empty string if no modules are needed.
pub fn generate_keymap_json(gen: &FirmwareGenerator) -> String {
    if !gen.layout.palette_fx.enabled {
        return String::new();
    }

    // Use serde_json to produce compact valid JSON
    let modules = serde_json::json!({
        "modules": ["getreuer/palettefx"]
    });

    serde_json::to_string_pretty(&modules).unwrap_or_default()
}
