//! Tests for the firmware generator.
//!
//! Auto-extracted from the original 2921-line generator.rs and re-homed
//! into this file. Tests use `FirmwareGenerator::new(...)` and verify
//! byte-identical golden fixtures in the generated keymap.c / config.h.

use super::*;
use crate::models::keyboard_geometry::KeyGeometry;
use crate::models::layer::{KeyDefinition, Layer, Position};
use crate::models::RgbColor;
use std::path::PathBuf;

fn create_test_setup() -> (
    Layout,
    KeyboardGeometry,
    VisualLayoutMapping,
    Config,
    KeycodeDb,
) {
    let mut layout = Layout::new("Test").unwrap();

    // Set keyboard metadata needed for firmware generation
    layout.metadata.keyboard = Some("test".to_string());
    layout.metadata.layout_variant = Some("LAYOUT".to_string());
    layout.metadata.keymap_name = Some("default".to_string());
    layout.metadata.output_format = Some("uf2".to_string());

    let mut layer = Layer::new(0, "Base", RgbColor::new(255, 255, 255)).unwrap();
    layer.add_key(KeyDefinition::new(Position::new(0, 0), "KC_A"));
    layer.add_key(KeyDefinition::new(Position::new(0, 1), "KC_B"));
    layout.add_layer(layer).unwrap();

    let mut geometry = KeyboardGeometry::new("test", "LAYOUT", 2, 2);
    geometry.add_key(KeyGeometry::new((0, 0), 0, 0.0, 0.0));
    geometry.add_key(KeyGeometry::new((0, 1), 1, 1.0, 0.0));
    geometry.encoder_count = 4; // Set encoder count for tests

    let mapping = VisualLayoutMapping::build(&geometry);

    let mut config = Config::default();
    config.paths.qmk_firmware = Some(PathBuf::from("/tmp/qmk_test"));

    let keycode_db = KeycodeDb::load().expect("Failed to load keycode database");

    (layout, geometry, mapping, config, keycode_db)
}

#[test]
fn test_generate_keymap_c() {
    let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);

    let keymap_c = generator.generate_keymap_c().unwrap();

    // Verify header
    assert!(keymap_c.contains("// Generated by lazyqmk"));
    assert!(keymap_c.contains("// Layout: Test"));
    assert!(keymap_c.contains("#include QMK_KEYBOARD_H"));

    // Verify keymap structure
    assert!(keymap_c.contains("const uint16_t PROGMEM keymaps[]"));
    assert!(keymap_c.contains("[0] = LAYOUT("));
    assert!(keymap_c.contains("KC_A"));
    assert!(keymap_c.contains("KC_B"));

    // Verify encoder_map is included
    assert!(keymap_c.contains("#ifdef ENCODER_MAP_ENABLE"));
    assert!(keymap_c.contains("const uint16_t PROGMEM encoder_map[]"));
    assert!(keymap_c.contains("ENCODER_CCW_CW(RM_NEXT, RM_PREV)"));
    assert!(keymap_c.contains("#endif"));

    // Verify RGB matrix base color table is included for RGB keyboards
    assert!(keymap_c.contains("#ifdef RGB_MATRIX_ENABLE"));
    assert!(keymap_c.contains("const uint8_t PROGMEM layer_base_colors"));
    assert!(keymap_c.contains("#endif"));
}

#[test]
fn test_generate_merged_config_h_sets_default_mode_when_colored_and_rgb() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Mark layout as "colored" by changing the default color
    // and adding a category used by a key.
    let nav_color = RgbColor::new(0, 255, 0);
    let category = crate::models::Category::new("navigation", "Navigation", nav_color).unwrap();
    layout.add_category(category).unwrap();
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 1))
        .unwrap()
        .category_id = Some("navigation".to_string());

    // RGB-capable geometry: already has two keys in create_test_setup.
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    assert!(config_h.contains("RGB_MATRIX_TUI_LAYER_COLORS"));
    assert!(config_h.contains("#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS"));
}

#[test]
fn test_generate_merged_config_h_does_not_set_default_mode_without_colors_or_rgb() {
    let (layout, mut geometry, mapping, config, keycode_db) = create_test_setup();

    // Remove all keys from geometry so has_rgb_matrix() is false.
    geometry.keys.clear();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    assert!(!config_h.contains("RGB_MATRIX_TUI_LAYER_COLORS"));
    assert!(!config_h.contains("RGB_MATRIX_DEFAULT_MODE"));
}

#[test]
fn test_generate_layer_colors_by_led_uses_resolved_colors() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add a category and assign it to the second key so we can
    // verify that resolve_key_color logic is respected.
    let nav_color = RgbColor::new(0, 255, 0);
    let category = crate::models::Category::new("navigation", "Navigation", nav_color).unwrap();
    layout.add_category(category).unwrap();

    // Update key on layer 0, position (0, 1) to use the category.
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 1))
        .unwrap()
        .category_id = Some("navigation".to_string());

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let colors_by_led = generator.generate_layer_colors_by_led(0).unwrap();

    assert_eq!(colors_by_led.len(), 2);
    // First key uses layer default color (white from create_test_setup).
    assert_eq!(colors_by_led[0], RgbColor::new(255, 255, 255));
    // Second key uses category color.
    assert_eq!(colors_by_led[1], nav_color);
}

#[test]
fn test_generate_rgb_matrix_color_table_structure() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add a second layer with a different default color
    let mut layer2 = Layer::new(1, "Navigation", RgbColor::new(0, 128, 255)).unwrap();
    layer2.add_key(KeyDefinition::new(Position::new(0, 0), "KC_LEFT"));
    layer2.add_key(KeyDefinition::new(Position::new(0, 1), "KC_RIGHT"));
    layout.add_layer(layer2).unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let color_table = generator.generate_rgb_matrix_color_table().unwrap();

    // Verify structure
    assert!(color_table.contains("#ifdef RGB_MATRIX_ENABLE"));
    assert!(color_table.contains("#endif"));
    assert!(color_table.contains("const uint8_t PROGMEM layer_base_colors[2][2][3]"));
    assert!(color_table.contains("layer_base_colors_layer_count = 2;"));

    // Verify layer 0 colors (white default)
    assert!(color_table.contains("{255, 255, 255}"));
    // Verify layer 1 colors (blue-ish default)
    assert!(color_table.contains("{  0, 128, 255}"));
}

#[test]
fn test_generate_rgb_matrix_color_table_empty_for_non_rgb() {
    let (layout, mut geometry, mapping, config, keycode_db) = create_test_setup();

    // Remove keys to simulate non-RGB keyboard
    geometry.keys.clear();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let color_table = generator.generate_rgb_matrix_color_table().unwrap();

    // Should be empty for non-RGB keyboards
    assert!(color_table.is_empty());
}

#[test]
fn test_layout_has_custom_colors_with_category() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Initially should have no custom colors (just white default)
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    assert!(!generator.layout_has_custom_colors());

    // Add a category
    let category =
        crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
    layout.add_category(category).unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    assert!(generator.layout_has_custom_colors());
}

#[test]
fn test_layout_has_custom_colors_with_layer_default() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Change layer default color from white
    layout.get_layer_mut(0).unwrap().default_color = RgbColor::new(128, 128, 128);

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    assert!(generator.layout_has_custom_colors());
}

#[test]
fn test_layout_has_custom_colors_with_key_override() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add key color override
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 0))
        .unwrap()
        .color_override = Some(RgbColor::new(255, 0, 0));

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    assert!(generator.layout_has_custom_colors());
}

#[test]
fn test_generate_layer_colors_respects_priority_order() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Set up all four color levels for key at (0, 1):
    // 1. Global default is white (255, 255, 255)
    // 2. Layer default: blue
    layout.get_layer_mut(0).unwrap().default_color = RgbColor::new(0, 0, 255);

    // 3. Category: green
    let category =
        crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
    layout.add_category(category).unwrap();
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 1))
        .unwrap()
        .category_id = Some("nav".to_string());

    // 4. Key override: red (highest priority)
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 1))
        .unwrap()
        .color_override = Some(RgbColor::new(255, 0, 0));

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let colors = generator.generate_layer_colors_by_led(0).unwrap();

    // Key at LED 0 should use layer default (blue) since no category or override
    assert_eq!(colors[0], RgbColor::new(0, 0, 255));

    // Key at LED 1 should use override (red) - highest priority
    assert_eq!(colors[1], RgbColor::new(255, 0, 0));
}

#[test]
fn test_keymap_c_includes_rgb_table_when_rgb_enabled() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add category to trigger custom colors
    let category =
        crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
    layout.add_category(category).unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should include RGB matrix color table
    assert!(keymap_c.contains("#ifdef RGB_MATRIX_ENABLE"));
    assert!(keymap_c.contains("layer_base_colors"));
    assert!(keymap_c.contains("layer_base_colors_layer_count"));
}

#[test]
fn test_config_h_sets_tui_layer_colors_mode() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add category to trigger custom colors
    let category =
        crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
    layout.add_category(category).unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    // Should set the TUI layer colors mode as default
    assert!(config_h.contains("RGB_MATRIX_TUI_LAYER_COLORS"));
    assert!(config_h.contains("#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TUI_LAYER_COLORS"));
    assert!(config_h.contains("LAYER_BASE_COLORS_LAYER_COUNT 1"));
}

#[test]
fn test_multi_layer_color_table_generation() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Layer 0: White default
    // Layer 1: Red default
    let mut layer1 = Layer::new(1, "Red Layer", RgbColor::new(255, 0, 0)).unwrap();
    layer1.add_key(KeyDefinition::new(Position::new(0, 0), "KC_1"));
    layer1.add_key(KeyDefinition::new(Position::new(0, 1), "KC_2"));
    layout.add_layer(layer1).unwrap();

    // Layer 2: Green default
    let mut layer2 = Layer::new(2, "Green Layer", RgbColor::new(0, 255, 0)).unwrap();
    layer2.add_key(KeyDefinition::new(Position::new(0, 0), "KC_3"));
    layer2.add_key(KeyDefinition::new(Position::new(0, 1), "KC_4"));
    layout.add_layer(layer2).unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let color_table = generator.generate_rgb_matrix_color_table().unwrap();

    // Verify 3 layers
    assert!(color_table.contains("layer_base_colors[3][2][3]"));
    assert!(color_table.contains("layer_base_colors_layer_count = 3;"));

    // Verify each layer's colors are present
    assert!(color_table.contains("{255, 255, 255}")); // White
    assert!(color_table.contains("{255,   0,   0}")); // Red
    assert!(color_table.contains("{  0, 255,   0}")); // Green
}

#[test]
fn test_config_h_emits_tap_hold_settings() {
    use crate::models::{TapHoldPreset, TapHoldSettings};

    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Apply HomeRowMods preset
    layout.tap_hold_settings = TapHoldSettings::from_preset(TapHoldPreset::HomeRowMods);

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    // Verify tap-hold settings are emitted
    assert!(config_h.contains("// Tap-Hold Configuration"));
    assert!(config_h.contains("#define TAPPING_TERM 175"));
    assert!(config_h.contains("#define QUICK_TAP_TERM 120"));
    assert!(config_h.contains("#define PERMISSIVE_HOLD"));
    assert!(config_h.contains("#define RETRO_TAPPING"));
    assert!(config_h.contains("#define FLOW_TAP_TERM 150"));
    assert!(config_h.contains("#define CHORDAL_HOLD"));
}

#[test]
fn test_config_h_does_not_emit_default_tap_hold() {
    let (layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Layout has default tap-hold settings
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    // Should NOT contain tap-hold defines
    assert!(!config_h.contains("TAPPING_TERM"));
    assert!(!config_h.contains("QUICK_TAP_TERM"));
    assert!(!config_h.contains("PERMISSIVE_HOLD"));
    assert!(!config_h.contains("RETRO_TAPPING"));
}

#[test]
fn test_config_h_emits_hold_on_other_key_press() {
    use crate::models::{HoldDecisionMode, TapHoldSettings};

    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Set up custom tap-hold settings with HoldOnOtherKeyPress
    layout.tap_hold_settings = TapHoldSettings {
        tapping_term: 150,
        hold_mode: HoldDecisionMode::HoldOnOtherKeyPress,
        ..TapHoldSettings::default()
    };

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    assert!(config_h.contains("#define TAPPING_TERM 150"));
    assert!(config_h.contains("#define HOLD_ON_OTHER_KEY_PRESS"));
    assert!(!config_h.contains("PERMISSIVE_HOLD"));
}

#[test]
fn test_config_h_emits_tapping_toggle() {
    use crate::models::TapHoldSettings;

    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Change tapping toggle from default (5) to 3
    layout.tap_hold_settings = TapHoldSettings {
        tapping_toggle: 3,
        ..TapHoldSettings::default()
    };

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    assert!(config_h.contains("#define TAPPING_TOGGLE 3"));
}

#[test]
fn test_detect_required_headers_no_language_keycodes() {
    let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);

    let headers = generator.detect_required_headers();
    assert!(headers.is_empty());
}

#[test]
fn test_detect_required_headers_german_keycodes() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add German keycodes to layer
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 0))
        .unwrap()
        .keycode = "DE_Y".to_string();

    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 1))
        .unwrap()
        .keycode = "DE_UDIA".to_string();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let headers = generator.detect_required_headers();

    assert_eq!(headers.len(), 1);
    assert!(headers.iter().any(|h| h.contains("keymap_german")));
}

#[test]
fn test_detect_required_headers_german_in_layer_tap() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add German keycode inside LT()
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 0))
        .unwrap()
        .keycode = "LT(1, DE_A)".to_string();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let headers = generator.detect_required_headers();

    assert_eq!(headers.len(), 1);
    assert!(headers.iter().any(|h| h.contains("keymap_german")));
}

#[test]
fn test_generate_keymap_c_includes_language_headers() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add German keycode
    layout
        .get_layer_mut(0)
        .unwrap()
        .get_key_mut(Position::new(0, 0))
        .unwrap()
        .keycode = "DE_Y".to_string();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Verify the German header is included
    assert!(keymap_c.contains("#include QMK_KEYBOARD_H"));
    assert!(keymap_c.contains("#include \"keymap_extras/keymap_german.h\""));
}

#[test]
fn test_generate_keymap_c_no_extra_headers_without_language_keycodes() {
    let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should only have the standard include
    assert!(keymap_c.contains("#include QMK_KEYBOARD_H"));
    assert!(!keymap_c.contains("keymap_extras"));
}

// === Idle Effect Tests ===

#[test]
fn test_idle_effect_disabled_no_code() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();
    layout.idle_effect_settings.enabled = false;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should not contain idle effect code
    assert!(!keymap_c.contains("idle_state_t"));
    assert!(!keymap_c.contains("IDLE_STATE_ACTIVE"));
}

#[test]
fn test_idle_effect_enabled_generates_code() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();
    layout.idle_effect_settings.enabled = true;
    layout.idle_effect_settings.idle_timeout_ms = 30_000;
    layout.idle_effect_settings.idle_effect_duration_ms = 60_000;
    layout.idle_effect_settings.idle_effect_mode = crate::models::RgbMatrixEffect::Breathing;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should contain idle effect state machine
    assert!(keymap_c.contains("idle_state_t"));
    assert!(keymap_c.contains("IDLE_STATE_ACTIVE"));
    assert!(keymap_c.contains("IDLE_STATE_IDLE_EFFECT"));
    assert!(keymap_c.contains("IDLE_STATE_OFF"));
    assert!(keymap_c.contains("matrix_scan_user"));
    assert!(keymap_c.contains("process_record_user"));
    assert!(keymap_c.contains("keyboard_post_init_user"));
    assert!(keymap_c.contains("last_activity_time"));
}

#[test]
fn test_idle_effect_config_defines() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();
    layout.idle_effect_settings.enabled = true;
    layout.idle_effect_settings.idle_timeout_ms = 45_000;
    layout.idle_effect_settings.idle_effect_duration_ms = 180_000;
    layout.idle_effect_settings.idle_effect_mode = crate::models::RgbMatrixEffect::RainbowBeacon;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    // Should contain idle effect defines
    assert!(config_h.contains("#define LQMK_IDLE_TIMEOUT_MS 45000"));
    assert!(config_h.contains("#define LQMK_IDLE_EFFECT_DURATION_MS 180000"));
    assert!(config_h.contains("#define LQMK_IDLE_EFFECT_MODE RGB_MATRIX_RAINBOW_BEACON"));
}

#[test]
fn test_idle_effect_no_rgb_matrix_timeout_conflict() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();
    layout.idle_effect_settings.enabled = true;
    layout.rgb_timeout_ms = 60_000; // This should be ignored when idle effect is enabled

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    // Should contain idle effect defines
    assert!(config_h.contains("LQMK_IDLE_TIMEOUT_MS"));

    // Should NOT contain RGB_MATRIX_TIMEOUT when idle effect is enabled
    assert!(!config_h.contains("#define RGB_MATRIX_TIMEOUT"));
}

#[test]
fn test_rgb_matrix_timeout_when_idle_disabled() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();
    layout.idle_effect_settings.enabled = false;
    layout.rgb_timeout_ms = 120_000;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    // Should contain RGB_MATRIX_TIMEOUT when idle effect is disabled
    assert!(config_h.contains("#define RGB_MATRIX_TIMEOUT 120000"));

    // Should NOT contain idle effect defines
    assert!(!config_h.contains("LQMK_IDLE_TIMEOUT_MS"));
}

#[test]
fn test_idle_effect_restores_tui_colors() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add category to trigger custom colors
    let category =
        crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
    layout.add_category(category).unwrap();

    layout.idle_effect_settings.enabled = true;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should restore TUI layer colors mode on activity
    assert!(keymap_c.contains("rgb_matrix_mode_noeeprom(RGB_MATRIX_TUI_LAYER_COLORS)"));
}

#[test]
fn test_idle_effect_restores_default_mode() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();
    layout.idle_effect_settings.enabled = true;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should restore default mode when no custom colors
    assert!(keymap_c.contains("rgb_matrix_mode_noeeprom(RGB_MATRIX_DEFAULT_MODE)"));
}

#[test]
fn test_idle_effect_no_rgb_keyboard() {
    let (mut layout, mut geometry, mapping, config, keycode_db) = create_test_setup();

    // Remove keys to simulate non-RGB keyboard
    geometry.keys.clear();

    layout.idle_effect_settings.enabled = true;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();
    let config_h = generator.generate_merged_config_h().unwrap();

    // Should not generate idle effect code for non-RGB keyboard
    assert!(!keymap_c.contains("idle_state_t"));
    assert!(!config_h.contains("LQMK_IDLE_TIMEOUT_MS"));
}

// === Combo Tests ===

#[test]
fn test_combo_disabled_no_code() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();
    layout.combo_settings.enabled = false;

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should not contain combo code
    assert!(!keymap_c.contains("COMBO_ENABLE"));
    assert!(!keymap_c.contains("combo_events"));
}

#[test]
fn test_combo_enabled_generates_code() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Enable combos and add a combo definition
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::DisableEffects,
        ))
        .unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should contain combo structures
    assert!(keymap_c.contains("#ifdef COMBO_ENABLE"));
    assert!(keymap_c.contains("enum combo_events"));
    assert!(keymap_c.contains("COMBO_0"));
    assert!(keymap_c.contains("combo_0_keys"));
    assert!(keymap_c.contains("key_combos"));
    assert!(keymap_c.contains("combo_state"));
    assert!(keymap_c.contains("process_combo_event"));
    assert!(keymap_c.contains("get_highest_layer(layer_state) != 0"));
    assert!(keymap_c.contains("#endif // COMBO_ENABLE"));
}

#[test]
fn test_combo_multiple_combos() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Enable combos and add two combos
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::with_duration(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::DisableEffects,
            500,
        ))
        .unwrap();
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::with_duration(
            Position::new(0, 0),
            Position::new(1, 0),
            crate::models::ComboAction::Bootloader,
            1000,
        ))
        .unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should contain both combos
    assert!(keymap_c.contains("COMBO_0"));
    assert!(keymap_c.contains("COMBO_1"));
    assert!(keymap_c.contains("combo_0_keys"));
    assert!(keymap_c.contains("combo_1_keys"));
    assert!(keymap_c.contains("elapsed >= 500"));
    assert!(keymap_c.contains("elapsed >= 1000"));
}

#[test]
fn test_combo_actions_generated() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add a category to enable TUI layer colors
    let category =
        crate::models::Category::new("nav", "Navigation", RgbColor::new(0, 255, 0)).unwrap();
    layout.add_category(category).unwrap();

    // Enable combos with all action types
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::DisableEffects,
        ))
        .unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // DisableEffects should revert to TUI layer colors
    assert!(keymap_c.contains("rgb_matrix_mode_noeeprom(RGB_MATRIX_TUI_LAYER_COLORS)"));
}

#[test]
fn test_combo_config_h_defines() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Enable combos and add a combo
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::DisableEffects,
        ))
        .unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let config_h = generator.generate_merged_config_h().unwrap();

    // Should contain combo defines (COMBO_ENABLE is in rules.mk, not config.h)
    assert!(config_h.contains("// Combo Configuration"));
    assert!(
        !config_h.contains("#define COMBO_ENABLE"),
        "COMBO_ENABLE must not appear in config.h — it belongs in rules.mk"
    );
    assert!(config_h.contains("#define COMBO_COUNT 1"));
}

#[test]
fn test_combo_uses_keycodes_from_base_layer() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Enable combos and add a combo
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::Bootloader,
        ))
        .unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();

    // Should use the keycodes from base layer (KC_A and KC_B from create_test_setup)
    assert!(keymap_c.contains("combo_0_keys[] = {KC_A, KC_B, COMBO_END}"));
    assert!(keymap_c.contains("reset_keyboard()"));
}

#[test]
fn test_combo_placeholders_not_emitted() {
    // Regression test: when non-contiguous combo indices are defined
    // (e.g. only Combo 2 and Combo 3, skipping Combo 1), the parser uses
    // resize_with to grow the vec and inserts placeholder entries for the
    // gaps.  Those placeholders must never appear in the generated C output.
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    layout.combo_settings.enabled = true;

    // Manually simulate what the parser does for non-contiguous indices:
    // insert a placeholder at index 0, then two real combos at 1 and 2.
    layout
        .combo_settings
        .combos
        .push(crate::models::ComboDefinition::new_placeholder());
    layout
        .combo_settings
        .combos
        .push(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::DisableEffects,
        ));
    layout
        .combo_settings
        .combos
        .push(crate::models::ComboDefinition::new(
            Position::new(1, 0),
            Position::new(1, 1),
            crate::models::ComboAction::Bootloader,
        ));

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let keymap_c = generator.generate_keymap_c().unwrap();
    let config_h = generator.generate_merged_config_h().unwrap();

    // Only two real combos should be emitted (re-indexed 0 and 1)
    assert!(keymap_c.contains("COMBO_0"), "COMBO_0 should be present");
    assert!(keymap_c.contains("COMBO_1"), "COMBO_1 should be present");
    // No phantom COMBO_2 from a third slot
    assert!(
        !keymap_c.contains("COMBO_2"),
        "phantom COMBO_2 must not appear"
    );
    // Keys array for the placeholder must not be generated
    assert!(
        !keymap_c.contains("combo_2_keys"),
        "phantom combo_2_keys must not appear"
    );
    // COMBO_COUNT must reflect only the 2 real combos
    assert!(
        config_h.contains("#define COMBO_COUNT 2"),
        "COMBO_COUNT must be 2, got: {}",
        config_h
    );
}

// === rules.mk Tests ===

#[test]
fn test_rules_mk_empty_when_no_features() {
    let (layout, geometry, mapping, config, keycode_db) = create_test_setup();
    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);

    let rules_mk = generator.generate_rules_mk();
    assert!(
        rules_mk.is_empty(),
        "rules.mk should be empty when no features are enabled, got: {rules_mk}"
    );
}

#[test]
fn test_rules_mk_combo_enable() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Enable combos and add a real combo
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::Bootloader,
        ))
        .unwrap();

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let rules_mk = generator.generate_rules_mk();

    assert!(
        rules_mk.contains("COMBO_ENABLE = yes"),
        "rules.mk should contain COMBO_ENABLE = yes, got: {rules_mk}"
    );
    assert!(
        !rules_mk.contains("TAP_DANCE_ENABLE"),
        "rules.mk should not contain TAP_DANCE_ENABLE when no tap dances, got: {rules_mk}"
    );
}

#[test]
fn test_rules_mk_tap_dance_enable() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add a tap dance
    layout
        .tap_dances
        .push(crate::models::TapDanceAction::new("TD_TEST", "KC_A"));

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let rules_mk = generator.generate_rules_mk();

    assert!(
        rules_mk.contains("TAP_DANCE_ENABLE = yes"),
        "rules.mk should contain TAP_DANCE_ENABLE = yes, got: {rules_mk}"
    );
    assert!(
        !rules_mk.contains("COMBO_ENABLE"),
        "rules.mk should not contain COMBO_ENABLE when no combos, got: {rules_mk}"
    );
}

#[test]
fn test_rules_mk_both_features() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Enable combos
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .add_combo(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::DisableEffects,
        ))
        .unwrap();

    // Add a tap dance
    layout
        .tap_dances
        .push(crate::models::TapDanceAction::new("TD_TEST", "KC_A"));

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let rules_mk = generator.generate_rules_mk();

    assert!(
        rules_mk.contains("COMBO_ENABLE = yes"),
        "rules.mk should contain COMBO_ENABLE = yes, got: {rules_mk}"
    );
    assert!(
        rules_mk.contains("TAP_DANCE_ENABLE = yes"),
        "rules.mk should contain TAP_DANCE_ENABLE = yes, got: {rules_mk}"
    );
    // Should have header
    assert!(
        rules_mk.contains("# Generated by"),
        "rules.mk should have a generated-by header, got: {rules_mk}"
    );
}

#[test]
fn test_rules_mk_combos_disabled_no_enable() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Add combos but keep enabled = false
    layout.combo_settings.enabled = false;
    layout
        .combo_settings
        .combos
        .push(crate::models::ComboDefinition::new(
            Position::new(0, 0),
            Position::new(0, 1),
            crate::models::ComboAction::Bootloader,
        ));

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let rules_mk = generator.generate_rules_mk();

    assert!(
        rules_mk.is_empty(),
        "rules.mk should be empty when combos are disabled, got: {rules_mk}"
    );
}

#[test]
fn test_rules_mk_only_placeholder_combos_no_enable() {
    let (mut layout, geometry, mapping, config, keycode_db) = create_test_setup();

    // Enable combos but only add placeholder combos
    layout.combo_settings.enabled = true;
    layout
        .combo_settings
        .combos
        .push(crate::models::ComboDefinition::new_placeholder());

    let generator = FirmwareGenerator::new(&layout, &geometry, &mapping, &config, &keycode_db);
    let rules_mk = generator.generate_rules_mk();

    assert!(
        rules_mk.is_empty(),
        "rules.mk should be empty when only placeholder combos exist, got: {rules_mk}"
    );
}
